public class Control_Extend {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object arrayExtend = FFI_STUB;
    public static Object arrayExtend(Object... args) { return null; }

public static final Object extendFn = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("extend", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (w_3_i3) -> ((java.util.function.Function<Object, Object>) (f_1_i1)).apply((java.util.function.Function<Object, Object>) (w_prime__4_i4) -> ((java.util.function.Function<Object, Object>) (g_2_i2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(w_3_i3))).apply(w_prime__4_i4)))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_1_i5) -> Data_Functor.functorFn); }};
public static final Object extendArray = new java.util.LinkedHashMap<String, Object>() {{ put("extend", Control_Extend.arrayExtend); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Functor.functorArray); }};
public static final Object extend = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("extend");
public static final Object extendFlipped = (java.util.function.Function<Object, Object>) (dictExtend_0_i0) -> (java.util.function.Function<Object, Object>) (w_1_i1) -> (java.util.function.Function<Object, Object>) (f_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictExtend_0_i0).get("extend"))).apply(f_2_i2))).apply(w_1_i1);
public static final Object duplicate = (java.util.function.Function<Object, Object>) (dictExtend_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictExtend_0_i0).get("extend"))).apply((java.util.function.Function<Object, Object>) (x_1_i1) -> x_1_i1);
public static final Object composeCoKleisliFlipped = (java.util.function.Function<Object, Object>) (dictExtend_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (w_3_i3) -> ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictExtend_0_i0).get("extend"))).apply(g_2_i2))).apply(w_3_i3));
public static final Object composeCoKleisli = (java.util.function.Function<Object, Object>) (dictExtend_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (w_3_i3) -> ((java.util.function.Function<Object, Object>) (g_2_i2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictExtend_0_i0).get("extend"))).apply(f_1_i1))).apply(w_3_i3));
}
