public class Control_Monad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object whenM = (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bind1_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object Applicative0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mb_3_i3) -> (java.util.function.Function<Object, Object>) (m_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1_i1).get("bind"))).apply(mb_3_i3))).apply((java.util.function.Function<Object, Object>) (b_5_i5) -> ( ((Boolean) (b_5_i5)) ? m_4_i4 : ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2_i2).get("pure"))).apply(Data_Unit.unit))); }).get(); }).get();
public static final Object unlessM = (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bind1_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object Applicative0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mb_3_i3) -> (java.util.function.Function<Object, Object>) (m_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1_i1).get("bind"))).apply(mb_3_i3))).apply((java.util.function.Function<Object, Object>) (b_5_i5) -> ( ((Boolean) (!(((Boolean) (b_5_i5))))) ? m_4_i4 : ( ((Boolean) (b_5_i5)) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2_i2).get("pure"))).apply(Data_Unit.unit) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get(); }).get();
public static final Object monadProxy = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Applicative.applicativeProxy); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Control_Bind.bindProxy); }};
public static final Object monadFn = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Applicative.applicativeFn); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Control_Bind.bindFn); }};
public static final Object monadArray = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Applicative.applicativeArray); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Control_Bind.bindArray); }};
public static final Object liftM1 = (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bind1_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object Applicative0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_3_i3) -> (java.util.function.Function<Object, Object>) (a_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1_i1).get("bind"))).apply(a_4_i4))).apply((java.util.function.Function<Object, Object>) (a_prime__5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2_i2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_3_i3)).apply(a_prime__5_i5))); }).get(); }).get();
public static final Object ap = (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bind1_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object Applicative0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0_i0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_3_i3) -> (java.util.function.Function<Object, Object>) (a_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1_i1).get("bind"))).apply(f_3_i3))).apply((java.util.function.Function<Object, Object>) (f_prime__5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1_i1).get("bind"))).apply(a_4_i4))).apply((java.util.function.Function<Object, Object>) (a_prime__6_i6) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2_i2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__5_i5)).apply(a_prime__6_i6)))); }).get(); }).get();
}
