public class Control_Biapply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object biapplyTuple = new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) ((((Data_Tuple.Tuple) v_0_i0).value0))).apply((((Data_Tuple.Tuple) v1_1_i1).value0)), ((java.util.function.Function<Object, Object>) ((((Data_Tuple.Tuple) v_0_i0).value1))).apply((((Data_Tuple.Tuple) v1_1_i1).value1)))); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Bifunctor.bifunctorTuple); }};
public static final Object biapply = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("biapply");
public static final Object biapplyFirst = (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bifunctor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2_i2) -> (java.util.function.Function<Object, Object>) (b_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bifunctor0_1_i1).get("bimap"))).apply((java.util.function.Function<Object, Object>) (v_4_i4) -> (java.util.function.Function<Object, Object>) (x_5_i5) -> x_5_i5))).apply((java.util.function.Function<Object, Object>) (v_4_i6) -> (java.util.function.Function<Object, Object>) (x_5_i7) -> x_5_i7))).apply(a_2_i2)))).apply(b_3_i3); }).get();
public static final Object biapplySecond = (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bifunctor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2_i2) -> (java.util.function.Function<Object, Object>) (b_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bifunctor0_1_i1).get("bimap"))).apply(Data_Function.$const))).apply(Data_Function.$const))).apply(a_2_i2)))).apply(b_3_i3); }).get();
public static final Object bilift2 = (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bifunctor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (g_3_i3) -> (java.util.function.Function<Object, Object>) (a_4_i4) -> (java.util.function.Function<Object, Object>) (b_5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bifunctor0_1_i1).get("bimap"))).apply(f_2_i2))).apply(g_3_i3))).apply(a_4_i4)))).apply(b_5_i5); }).get();
public static final Object bilift3 = (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Bifunctor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (g_3_i3) -> (java.util.function.Function<Object, Object>) (a_4_i4) -> (java.util.function.Function<Object, Object>) (b_5_i5) -> (java.util.function.Function<Object, Object>) (c_6_i6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bifunctor0_1_i1).get("bimap"))).apply(f_2_i2))).apply(g_3_i3))).apply(a_4_i4)))).apply(b_5_i5)))).apply(c_6_i6); }).get();
}
