public class Control_Bind {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object arrayBind = FFI_STUB;
    public static Object arrayBind(Object... args) { return null; }

public static final Object discard = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("discard");
public static final Object bindProxy = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Type_Proxy.Proxy()); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Control_Apply.applyProxy); }};
public static final Object bindFn = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (m_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_1_i1)).apply(((java.util.function.Function<Object, Object>) (m_0_i0)).apply(x_2_i2)))).apply(x_2_i2)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> Control_Apply.applyFn); }};
public static final Object bindArray = new java.util.LinkedHashMap<String, Object>() {{ put("bind", Control_Bind.arrayBind); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Apply.applyArray); }};
public static final Object bind = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("bind");
public static final Object bindFlipped = (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (a_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind"))).apply(a_2_i2))).apply(b_1_i1);
public static final Object composeKleisliFlipped = (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (a_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind"))).apply(((java.util.function.Function<Object, Object>) (g_2_i2)).apply(a_3_i3)))).apply(f_1_i1);
public static final Object composeKleisli = (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (a_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind"))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(a_3_i3)))).apply(g_2_i2);
public static final Object discardProxy = new java.util.LinkedHashMap<String, Object>() {{ put("discard", (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind")); }};
public static final Object discardUnit = new java.util.LinkedHashMap<String, Object>() {{ put("discard", (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind")); }};
public static final Object ifM = (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> (java.util.function.Function<Object, Object>) (cond_1_i1) -> (java.util.function.Function<Object, Object>) (t_2_i2) -> (java.util.function.Function<Object, Object>) (f_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind"))).apply(cond_1_i1))).apply((java.util.function.Function<Object, Object>) (cond_prime__4_i4) -> ( ((Boolean) (cond_prime__4_i4)) ? t_2_i2 : f_3_i3));
public static final Object join = (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> (java.util.function.Function<Object, Object>) (m_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBind_0_i0).get("bind"))).apply(m_1_i1))).apply((java.util.function.Function<Object, Object>) (x_2_i2) -> x_2_i2);
}
