public class Control_Monad_ST_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object bind_ = FFI_STUB;
    public static Object bind_(Object... args) { return null; }
    public static Object $for = FFI_STUB;
    public static Object $for(Object... args) { return null; }
    public static Object foreach = FFI_STUB;
    public static Object foreach(Object... args) { return null; }
    public static Object map_ = FFI_STUB;
    public static Object map_(Object... args) { return null; }
    public static Object modifyImpl = FFI_STUB;
    public static Object modifyImpl(Object... args) { return null; }
    public static Object $new = FFI_STUB;
    public static Object $new(Object... args) { return null; }
    public static Object pure_ = FFI_STUB;
    public static Object pure_(Object... args) { return null; }
    public static Object read = FFI_STUB;
    public static Object read(Object... args) { return null; }
    public static Object run = FFI_STUB;
    public static Object run(Object... args) { return null; }
    public static Object $while = FFI_STUB;
    public static Object $while(Object... args) { return null; }
    public static Object write = FFI_STUB;
    public static Object write(Object... args) { return null; }

public static final Object modifyprime = Control_Monad_ST_Internal.modifyImpl;
public static final Object modify = (java.util.function.Function<Object, Object>) (f_0_i0) -> ((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.modifyImpl)).apply((java.util.function.Function<Object, Object>) (s_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object s_prime__2_i2 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(s_1_i1); return new java.util.LinkedHashMap<String, Object>() {{ put("state", s_prime__2_i2); put("value", s_prime__2_i2); }}; }).get());
public static final Object functorST = new java.util.LinkedHashMap<String, Object>() {{ put("map", Control_Monad_ST_Internal.map_); }};
public static final Object monadST = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Monad_ST_Internal.applicativeST); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Control_Monad_ST_Internal.bindST); }};
public static final Object bindST = new java.util.LinkedHashMap<String, Object>() {{ put("bind", Control_Monad_ST_Internal.bind_); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Monad_ST_Internal.applyST); }};
public static final Object applyST = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (a_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object f_prime__2_i2 = f_0_i0; return ((java.util.function.Supplier<Object>) () -> { Object a_prime__3_i3 = a_1_i1; return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.applicativeST).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__2_i2)).apply(a_prime__3_i3)); }).get(); }).get()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i4) -> Control_Monad_ST_Internal.functorST); }};
public static final Object applicativeST = new java.util.LinkedHashMap<String, Object>() {{ put("pure", Control_Monad_ST_Internal.pure_); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Control_Monad_ST_Internal.applyST); }};
public static final Object semigroupST = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a_1_i1) -> (java.util.function.Function<Object, Object>) (b_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object f_prime__3_i4 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = a_1_i1; return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(__local_var_3_i3); }).get(); return ((java.util.function.Supplier<Object>) () -> { Object a_prime__4_i5 = b_2_i2; return ((java.util.function.Function<Object, Object>) (f_prime__3_i4)).apply(a_prime__4_i5); }).get(); }).get()); }};
public static final Object monadRecST = new java.util.LinkedHashMap<String, Object>() {{ put("tailRecM", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (a_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(a_1_i1); return ((java.util.function.Supplier<Object>) () -> { Object r_3_i4 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = __local_var_2_i2; return null /* TODO: PrimEffect */; }).get(); return ((java.util.function.Supplier<Object>) () -> { Object _dollar___unused_4_i9 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i5 = null /* TODO: PrimEffect */; return (__local_var_4_i5 instanceof Control_Monad_Rec_Class.Loop); }).get()))).apply(((java.util.function.Supplier<Object>) () -> { Object v_4_i6 = null /* TODO: PrimEffect */; return ( ((Boolean) ((v_4_i6 instanceof Control_Monad_Rec_Class.Loop))) ? ((java.util.function.Supplier<Object>) () -> { Object e_5_i7 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply((((Control_Monad_Rec_Class.Loop) v_4_i6).value0)); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_6_i8 = null /* TODO: PrimEffect */; return Data_Unit.unit; }).get(); }).get() : ( ((Boolean) ((v_4_i6 instanceof Control_Monad_Rec_Class.Done))) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); }).get()); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_5_i10 = null /* TODO: PrimEffect */; return ( ((Boolean) ((__local_var_5_i10 instanceof Control_Monad_Rec_Class.Done))) ? (((Control_Monad_Rec_Class.Done) __local_var_5_i10).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()); }).get(); }).get(); }).get(); }).get()); put("Monad0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i11) -> Control_Monad_ST_Internal.monadST); }};
public static final Object monoidST = (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupST1_1_i7 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a_2_i2) -> (java.util.function.Function<Object, Object>) (b_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object f_prime__4_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i4 = a_2_i2; return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("append"))).apply(__local_var_4_i4); }).get(); return ((java.util.function.Supplier<Object>) () -> { Object a_prime__5_i6 = b_3_i3; return ((java.util.function.Function<Object, Object>) (f_prime__4_i5)).apply(a_prime__5_i6); }).get(); }).get()); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i8 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("mempty"); return __local_var_2_i8; }).get()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i9) -> semigroupST1_1_i7); }}; }).get();
}
