public class Data_Maybe {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Nothing {
            
            public Nothing() {
                
            }
        }
public static final class Just {
            public final Object value0;
            public Just(Object value0) {
                this.value0 = value0;
            }
        }
public static final Object Nothing = new Data_Maybe.Nothing();
public static final Object Just = (java.util.function.Function<Object, Object>) (value0_i0) -> new Data_Maybe.Just(value0_i0);
public static final Object showMaybe = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Just))) ? (((String) ((((String) ("(Just ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply((((Data_Maybe.Just) v_1_i1).value0))))))) + ((String) (")"))) : ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Nothing))) ? "Nothing" : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object semigroupMaybe = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Nothing))) ? v1_2_i2 : ( ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Nothing))) ? v_1_i1 : ( ((Boolean) ((((Boolean) ((v_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply((((Data_Maybe.Just) v_1_i1).value0)))).apply((((Data_Maybe.Just) v1_2_i2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); }};
public static final Object optional = (java.util.function.Function<Object, Object>) (dictAlt_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Functor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlt_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictApplicative_2_i2) -> (java.util.function.Function<Object, Object>) (a_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlt_0_i0).get("alt"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1_i1).get("map"))).apply(Data_Maybe.Just))).apply(a_3_i3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_2_i2).get("pure"))).apply(new Data_Maybe.Nothing())); }).get();
public static final Object monoidMaybe = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupMaybe1_1_i3 = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Nothing))) ? v1_2_i2 : ( ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Nothing))) ? v_1_i1 : ( ((Boolean) ((((Boolean) ((v_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply((((Data_Maybe.Just) v_1_i1).value0)))).apply((((Data_Maybe.Just) v1_2_i2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", new Data_Maybe.Nothing()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> semigroupMaybe1_1_i3); }}; }).get();
public static final Object maybeprime = (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (v2_2_i2) -> ( ((Boolean) ((v2_2_i2 instanceof Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (v_0_i0)).apply(Data_Unit.unit) : ( ((Boolean) ((v2_2_i2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply((((Data_Maybe.Just) v2_2_i2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object maybe = (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (v2_2_i2) -> ( ((Boolean) ((v2_2_i2 instanceof Data_Maybe.Nothing))) ? v_0_i0 : ( ((Boolean) ((v2_2_i2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply((((Data_Maybe.Just) v2_2_i2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object isNothing = (java.util.function.Function<Object, Object>) (v2_0_i0) -> ( ((Boolean) ((v2_0_i0 instanceof Data_Maybe.Nothing))) ? true : ( ((Boolean) ((v2_0_i0 instanceof Data_Maybe.Just))) ? false : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object isJust = (java.util.function.Function<Object, Object>) (v2_0_i0) -> ( ((Boolean) ((v2_0_i0 instanceof Data_Maybe.Nothing))) ? false : ( ((Boolean) ((v2_0_i0 instanceof Data_Maybe.Just))) ? true : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object genericMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("to", (java.util.function.Function<Object, Object>) (x_0_i0) -> ( ((Boolean) ((x_0_i0 instanceof Data_Generic_Rep.Inl))) ? new Data_Maybe.Nothing() : ( ((Boolean) ((x_0_i0 instanceof Data_Generic_Rep.Inr))) ? new Data_Maybe.Just((((Data_Generic_Rep.Inr) x_0_i0).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("from", (java.util.function.Function<Object, Object>) (x_0_i1) -> ( ((Boolean) ((x_0_i1 instanceof Data_Maybe.Nothing))) ? new Data_Generic_Rep.Inl(new Data_Generic_Rep.NoArguments()) : ( ((Boolean) ((x_0_i1 instanceof Data_Maybe.Just))) ? new Data_Generic_Rep.Inr((((Data_Maybe.Just) x_0_i1).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object functorMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v1_1_i1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0_i0)).apply((((Data_Maybe.Just) v1_1_i1).value0))) : new Data_Maybe.Nothing())); }};
public static final Object invariantMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ( ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (f_0_i0)).apply((((Data_Maybe.Just) v1_2_i2).value0))) : new Data_Maybe.Nothing())); }};
public static final Object fromMaybeprime = (java.util.function.Function<Object, Object>) (a_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Maybe.maybeprime)).apply(a_0_i0))).apply((java.util.function.Function<Object, Object>) (x_1_i1) -> x_1_i1);
public static final Object fromMaybe = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (v2_1_i1) -> ( ((Boolean) ((v2_1_i1 instanceof Data_Maybe.Nothing))) ? a_0_i0 : ( ((Boolean) ((v2_1_i1 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v2_1_i1).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object fromJust = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_1_i1).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get());
public static final Object extendMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("extend", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v1_1_i1 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0_i0)).apply(v1_1_i1)))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Maybe.functorMaybe); }};
public static final Object eqMaybe = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> ( ((Boolean) ((x_1_i1 instanceof Data_Maybe.Nothing))) ? (y_2_i2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2_i2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq"))).apply((((Data_Maybe.Just) x_1_i1).value0)))).apply((((Data_Maybe.Just) y_2_i2).value0)))))))))); }};
public static final Object ordMaybe = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqMaybe1_1_i4 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ( ((Boolean) ((x_2_i2 instanceof Data_Maybe.Nothing))) ? (y_3_i3 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_2_i2 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_3_i3 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("eq"))).apply((((Data_Maybe.Just) x_2_i2).value0)))).apply((((Data_Maybe.Just) y_3_i3).value0)))))))))); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_2_i5) -> (java.util.function.Function<Object, Object>) (y_3_i6) -> ( ((Boolean) ((x_2_i5 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3_i6 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_3_i6 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_2_i5 instanceof Data_Maybe.Just))) && ((Boolean) ((y_3_i6 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply((((Data_Maybe.Just) x_2_i5).value0)))).apply((((Data_Maybe.Just) y_3_i6).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> eqMaybe1_1_i4); }}; }).get();
public static final Object eq1Maybe = new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> ( ((Boolean) ((x_1_i1 instanceof Data_Maybe.Nothing))) ? (y_2_i2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2_i2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq"))).apply((((Data_Maybe.Just) x_1_i1).value0)))).apply((((Data_Maybe.Just) y_2_i2).value0)))))))))); }};
public static final Object ord1Maybe = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> ( ((Boolean) ((x_1_i1 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_2_i2 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_2_i2 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((y_2_i2 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply((((Data_Maybe.Just) x_1_i1).value0)))).apply((((Data_Maybe.Just) y_2_i2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> Data_Maybe.eq1Maybe); }};
public static final Object boundedMaybe = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object ordMaybe1_1_i9 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object eqMaybe1_2_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_3_i3) -> (java.util.function.Function<Object, Object>) (y_4_i4) -> ( ((Boolean) ((x_3_i3 instanceof Data_Maybe.Nothing))) ? (y_4_i4 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_3_i3 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_4_i4 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2_i2).get("eq"))).apply((((Data_Maybe.Just) x_3_i3).value0)))).apply((((Data_Maybe.Just) y_4_i4).value0)))))))))); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_3_i6) -> (java.util.function.Function<Object, Object>) (y_4_i7) -> ( ((Boolean) ((x_3_i6 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_4_i7 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_4_i7 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_3_i6 instanceof Data_Maybe.Just))) && ((Boolean) ((y_4_i7 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("compare"))).apply((((Data_Maybe.Just) x_3_i6).value0)))).apply((((Data_Maybe.Just) y_4_i7).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i8) -> eqMaybe1_2_i5); }}; }).get(); }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("top", new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("top"))); put("bottom", new Data_Maybe.Nothing()); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i10) -> ordMaybe1_1_i9); }}; }).get();
public static final Object applyMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((v1_1_i1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) ((((Data_Maybe.Just) v_0_i0).value0))).apply((((Data_Maybe.Just) v1_1_i1).value0))) : new Data_Maybe.Nothing()) : ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Maybe.functorMaybe); }};
public static final Object bindMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply((((Data_Maybe.Just) v_0_i0).value0)) : ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Maybe.applyMaybe); }};
public static final Object semiringMaybe = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("zero", new Data_Maybe.Nothing()); put("one", new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("one"))); put("add", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Nothing))) ? v1_2_i2 : ( ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Nothing))) ? v_1_i1 : ( ((Boolean) ((((Boolean) ((v_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2_i2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("add"))).apply((((Data_Maybe.Just) v_1_i1).value0)))).apply((((Data_Maybe.Just) v1_2_i2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("mul", (java.util.function.Function<Object, Object>) (x_1_i3) -> (java.util.function.Function<Object, Object>) (y_2_i4) -> ( ((Boolean) ((x_1_i3 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((y_2_i4 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("mul"))).apply((((Data_Maybe.Just) x_1_i3).value0)))).apply((((Data_Maybe.Just) y_2_i4).value0))) : new Data_Maybe.Nothing()) : new Data_Maybe.Nothing())); }};
public static final Object applicativeMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("pure", Data_Maybe.Just); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe.applyMaybe); }};
public static final Object monadMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe.applicativeMaybe); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Maybe.bindMaybe); }};
public static final Object altMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("alt", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Nothing))) ? v1_1_i1 : v_0_i0)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Maybe.functorMaybe); }};
public static final Object plusMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("empty", new Data_Maybe.Nothing()); put("Alt0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe.altMaybe); }};
public static final Object alternativeMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe.applicativeMaybe); put("Plus1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Maybe.plusMaybe); }};
}
