public class Data_Op {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Op = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object semigroupoidOp = new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply(((java.util.function.Function<Object, Object>) (v_0_i0)).apply(x_2_i2))); }};
public static final Object semigroupOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(x_3_i3)))).apply(((java.util.function.Function<Object, Object>) (g_2_i2)).apply(x_3_i3))); }};
public static final Object newtypeOp = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidOp = (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupFn_1_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (g_3_i3) -> (java.util.function.Function<Object, Object>) (x_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_2_i2)).apply(x_4_i4)))).apply(((java.util.function.Function<Object, Object>) (g_3_i3)).apply(x_4_i4))); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_2_i6) -> ((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("mempty")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> semigroupFn_1_i5); }}; }).get();
public static final Object contravariantOp = new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (v_1_i1)).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_2_i2))); }};
public static final Object categoryOp = new java.util.LinkedHashMap<String, Object>() {{ put("identity", (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0); put("Semigroupoid0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Op.semigroupoidOp); }};
}
