public class Data_Function {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object on = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (g_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0_i0)).apply(((java.util.function.Function<Object, Object>) (g_1_i1)).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (g_1_i1)).apply(y_3_i3));
public static final Object flip = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (a_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0_i0)).apply(a_2_i2))).apply(b_1_i1);
public static final Object $const = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> a_0_i0;
public static final Object applyN = (java.util.function.Function<Object, Object>) (f_0_i0) -> ((new java.util.function.Supplier<Object>() { class LetRecScope { Object go__go_1_i1; LetRecScope() { go__go_1_i1 = (java.util.function.Function<Object, Object>) (n_2_i2) -> (java.util.function.Function<Object, Object>) (acc_3_i2) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_n_2_i2 = n_2_i2; Object __tco_acc_3_i2 = acc_3_i2; while(true) { final Object __final_n_2_i2 = __tco_n_2_i2; final Object __final_acc_3_i2 = __tco_acc_3_i2; try { return ( ((Boolean) ((((Integer) (__final_n_2_i2)) <= ((Integer) (0))))) ? __final_acc_3_i2 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (go__go_1_i1)).apply((((Integer) (__final_n_2_i2)) - ((Integer) (1)))))).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(__final_acc_3_i2))); } catch (TcoLoop __tco_ex) { __tco_n_2_i2 = __tco_ex.args[0]; __tco_acc_3_i2 = __tco_ex.args[1]; } } }).get(); } } LetRecScope _scope = new LetRecScope(); Object go__go_1_i1 = _scope.go__go_1_i1; public Object get() { return go__go_1_i1; } })).get();
public static final Object applyFlipped = (java.util.function.Function<Object, Object>) (x_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(x_0_i0);
public static final Object apply = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_1_i1);
}
