public class Data_Divisible {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object divisiblePredicate = new java.util.LinkedHashMap<String, Object>() {{ put("conquer", (java.util.function.Function<Object, Object>) (v_0_i0) -> true); put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Divide.dividePredicate); }};
public static final Object divisibleOp = (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object divideOp_1_i8 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("divide", (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (v_3_i3) -> (java.util.function.Function<Object, Object>) (v1_4_i4) -> (java.util.function.Function<Object, Object>) (a_5_i5) -> ((java.util.function.Supplier<Object>) () -> { Object v2_6_i6 = ((java.util.function.Function<Object, Object>) (f_2_i2)).apply(a_5_i5); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_3_i3)).apply((((Data_Tuple.Tuple) v2_6_i6).value0))))).apply(((java.util.function.Function<Object, Object>) (v1_4_i4)).apply((((Data_Tuple.Tuple) v2_6_i6).value1))); }).get()); put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> Data_Op.contravariantOp); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("conquer", ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i9 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("mempty"); return (java.util.function.Function<Object, Object>) (v_3_i10) -> __local_var_2_i9; }).get()); put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i11) -> divideOp_1_i8); }}; }).get();
public static final Object divisibleEquivalence = new java.util.LinkedHashMap<String, Object>() {{ put("conquer", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> true); put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Divide.divideEquivalence); }};
public static final Object divisibleComparison = new java.util.LinkedHashMap<String, Object>() {{ put("conquer", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Ordering.EQ()); put("Divide0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Divide.divideComparison); }};
public static final Object conquer = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("conquer");
}
