public class Data_Ord {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Ord.java
    public static Object unsafeCompareImpl = (java.util.function.Function<Object, Object>) (lt) -> (java.util.function.Function<Object, Object>) (eq) -> (java.util.function.Function<Object, Object>) (gt) -> (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> {
        int cmp;
        if (x instanceof String && y instanceof String) {
            cmp = ((String) x).compareTo((String) y);
        } else if (x instanceof Integer && y instanceof Integer) {
            cmp = ((Integer) x).compareTo((Integer) y);
        } else if (x instanceof Double && y instanceof Double) {
            cmp = ((Double) x).compareTo((Double) y);
        } else if (x instanceof Boolean && y instanceof Boolean) {
            cmp = ((Boolean) x).compareTo((Boolean) y);
        } else {
            throw new RuntimeException("unsafeCompareImpl: Unsupported types " + x.getClass() + " and " + y.getClass());
        }
        if (cmp < 0) return lt;
        if (cmp > 0) return gt;
        return eq;
    };

    public static Object ordBooleanImpl = unsafeCompareImpl;
    public static Object ordIntImpl = unsafeCompareImpl;
    public static Object ordNumberImpl = unsafeCompareImpl;
    public static Object ordStringImpl = unsafeCompareImpl;
    public static Object ordCharImpl = unsafeCompareImpl;

    public static Object ordArrayImpl = (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Function<Object, Object>) (xs) -> (java.util.function.Function<Object, Object>) (ys) -> {
        Object[] arr1 = (Object[]) xs;
        Object[] arr2 = (Object[]) ys;
        int xlen = arr1.length;
        int ylen = arr2.length;
        int i = 0;
        while (i < xlen && i < ylen) {
            Object x = arr1[i];
            Object y = arr2[i];
            int o = (Integer) ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) f).apply(x)).apply(y);
            if (o != 0) {
                return o;
            }
            i++;
        }
        if (xlen == ylen) {
            return 0;
        } else if (xlen > ylen) {
            return -1;
        } else {
            return 1;
        }
    };


public static final Object ordVoid = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Ordering.EQ()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Eq.eqVoid); }};
public static final Object ordUnit = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Ordering.EQ()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Eq.eqUnit); }};
public static final Object ordString = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordStringImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Eq.eqString); }};
public static final Object ordRecordNil = new java.util.LinkedHashMap<String, Object>() {{ put("compareRecord", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (v2_2_i2) -> new Data_Ordering.EQ()); put("EqRecord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> Data_Eq.eqRowNil); }};
public static final Object ordProxy = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Ordering.EQ()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Eq.eqProxy); }};
public static final Object ordOrdering = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v_0_i0 instanceof Data_Ordering.LT))) ? ( ((Boolean) ((v1_1_i1 instanceof Data_Ordering.LT))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((v_0_i0 instanceof Data_Ordering.EQ))) ? ( ((Boolean) ((v1_1_i1 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((v1_1_i1 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : ( ((Boolean) ((v1_1_i1 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))) : ( ((Boolean) ((v_0_i0 instanceof Data_Ordering.GT))) ? ( ((Boolean) ((v1_1_i1 instanceof Data_Ordering.GT))) ? new Data_Ordering.EQ() : new Data_Ordering.GT()) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Ordering.eqOrdering); }};
public static final Object ordNumber = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Eq.eqNumber); }};
public static final Object ordInt = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Eq.eqInt); }};
public static final Object ordChar = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordCharImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Eq.eqChar); }};
public static final Object ordBoolean = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordBooleanImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Eq.eqBoolean); }};
public static final Object compareRecord = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("compareRecord");
public static final Object ordRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> (java.util.function.Function<Object, Object>) (dictOrdRecord_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object eqRec1_2_i2 = new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_1_i1).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)).get("eqRecord"))).apply(new Type_Proxy.Proxy())); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_1_i1).get("compareRecord"))).apply(new Type_Proxy.Proxy())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i3) -> eqRec1_2_i2); }}; }).get();
public static final Object compare1 = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("compare1");
public static final Object compare = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("compare");
public static final Object comparing = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(y_3_i3));
public static final Object greaterThan = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (a1_1_i1) -> (java.util.function.Function<Object, Object>) (a2_2_i2) -> (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2) instanceof Data_Ordering.GT);
public static final Object greaterThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (a1_1_i1) -> (java.util.function.Function<Object, Object>) (a2_2_i2) -> !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2) instanceof Data_Ordering.LT))));
public static final Object lessThan = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (a1_1_i1) -> (java.util.function.Function<Object, Object>) (a2_2_i2) -> (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2) instanceof Data_Ordering.LT);
public static final Object signum = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (dictRing_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object Semiring0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object zero_3_i3 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2_i2).get("zero"); return ((java.util.function.Supplier<Object>) () -> { Object Semiring01_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object one_5_i5 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2_i2).get("one"); return (java.util.function.Function<Object, Object>) (x_6_i6) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_6_i6))).apply(zero_3_i3) instanceof Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("sub"))).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(((java.util.LinkedHashMap<String, Object>) Semiring01_4_i4).get("one")) : ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_6_i6))).apply(zero_3_i3) instanceof Data_Ordering.GT))) ? one_5_i5 : x_6_i6)); }).get(); }).get(); }).get(); }).get();
public static final Object lessThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (a1_1_i1) -> (java.util.function.Function<Object, Object>) (a2_2_i2) -> !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2) instanceof Data_Ordering.GT))));
public static final Object max = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_1_i1))).apply(y_2_i2); return ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.LT))) ? y_2_i2 : ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.EQ))) ? x_1_i1 : ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.GT))) ? x_1_i1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get();
public static final Object min = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_1_i1))).apply(y_2_i2); return ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.LT))) ? x_1_i1 : ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.EQ))) ? x_1_i1 : ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.GT))) ? y_2_i2 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get();
public static final Object ordArray = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqArray_1_i1 = new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)).get("eq"))); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (xs_2_i2) -> (java.util.function.Function<Object, Object>) (ys_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_4_i4) -> (java.util.function.Function<Object, Object>) (y_5_i5) -> ((java.util.function.Supplier<Object>) () -> { Object v_6_i6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_4_i4))).apply(y_5_i5); return ( ((Boolean) ((v_6_i6 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_6_i6 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_6_i6 instanceof Data_Ordering.GT))) ? -1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()))).apply(xs_2_i2))).apply(ys_3_i3))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> eqArray_1_i1); }}; }).get();
public static final Object ord1Array = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (xs_1_i1) -> (java.util.function.Function<Object, Object>) (ys_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_3_i3) -> (java.util.function.Function<Object, Object>) (y_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object v_5_i5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(y_4_i4); return ( ((Boolean) ((v_5_i5 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_5_i5 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_5_i5 instanceof Data_Ordering.GT))) ? -1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()))).apply(xs_1_i1))).apply(ys_2_i2))); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i6) -> Data_Eq.eq1Array); }};
public static final Object ordRecordCons = (java.util.function.Function<Object, Object>) (dictOrdRecord_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqRowCons_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Eq.eqRowCons)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_0_i0).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> (java.util.function.Function<Object, Object>) (dictIsSymbol_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object eqRowCons1_4_i4 = ((java.util.function.Function<Object, Object>) (eqRowCons_1_i1)).apply(dictIsSymbol_3_i3); return (java.util.function.Function<Object, Object>) (dictOrd_5_i5) -> ((java.util.function.Supplier<Object>) () -> { Object eqRowCons2_6_i6 = ((java.util.function.Function<Object, Object>) (eqRowCons1_4_i4)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_5_i5).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return new java.util.LinkedHashMap<String, Object>() {{ put("compareRecord", (java.util.function.Function<Object, Object>) (v_7_i7) -> (java.util.function.Function<Object, Object>) (ra_8_i8) -> (java.util.function.Function<Object, Object>) (rb_9_i9) -> ((java.util.function.Supplier<Object>) () -> { Object key_10_i10 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_3_i3).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); return ((java.util.function.Supplier<Object>) () -> { Object left_11_i11 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_5_i5).get("compare"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_10_i10))).apply(ra_8_i8)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_10_i10))).apply(rb_9_i9)); return ( ((Boolean) (!(((Boolean) ((left_11_i11 instanceof Data_Ordering.EQ)))))) ? left_11_i11 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_0_i0).get("compareRecord"))).apply(new Type_Proxy.Proxy()))).apply(ra_8_i8))).apply(rb_9_i9)); }).get(); }).get()); put("EqRecord0", (java.util.function.Function<Object, Object>) (_dollar___unused_7_i12) -> eqRowCons2_6_i6); }}; }).get(); }).get(); }).get();
public static final Object clamp = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (low_1_i1) -> (java.util.function.Function<Object, Object>) (hi_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i5 = ((java.util.function.Supplier<Object>) () -> { Object v_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(low_1_i1))).apply(x_3_i3); return ( ((Boolean) ((v_4_i4 instanceof Data_Ordering.LT))) ? x_3_i3 : ( ((Boolean) ((v_4_i4 instanceof Data_Ordering.EQ))) ? low_1_i1 : ( ((Boolean) ((v_4_i4 instanceof Data_Ordering.GT))) ? low_1_i1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get(); return ((java.util.function.Supplier<Object>) () -> { Object v_5_i6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(hi_2_i2))).apply(__local_var_4_i5); return ( ((Boolean) ((v_5_i6 instanceof Data_Ordering.LT))) ? hi_2_i2 : ( ((Boolean) ((v_5_i6 instanceof Data_Ordering.EQ))) ? hi_2_i2 : ( ((Boolean) ((v_5_i6 instanceof Data_Ordering.GT))) ? __local_var_4_i5 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get(); }).get();
public static final Object between = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (low_1_i1) -> (java.util.function.Function<Object, Object>) (hi_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(low_1_i1) instanceof Data_Ordering.LT))) ? false : !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(hi_2_i2) instanceof Data_Ordering.GT)))));
public static final Object abs = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> (java.util.function.Function<Object, Object>) (dictRing_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object zero_2_i2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero"); return (java.util.function.Function<Object, Object>) (x_3_i3) -> ( ((Boolean) (!(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(zero_2_i2) instanceof Data_Ordering.LT)))))) ? x_3_i3 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("sub"))).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(x_3_i3)); }).get();
}
