public class Data_Unfoldable1 {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object unfoldr1ArrayImpl = FFI_STUB;
    public static Object unfoldr1ArrayImpl(Object... args) { return null; }

public static final Object unfoldr1 = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("unfoldr1");
public static final Object unfoldable1Maybe = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr1", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> new Data_Maybe.Just((((Data_Tuple.Tuple) ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(b_1_i1)).value0))); }};
public static final Object unfoldable1Array = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr1", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.unfoldr1ArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_0_i0).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd)); }};
public static final Object replicate1 = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0_i0) -> (java.util.function.Function<Object, Object>) (n_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0_i0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_3_i3) -> ( ((Boolean) ((((Integer) (i_3_i3)) <= ((Integer) (0))))) ? new Data_Tuple.Tuple(v_2_i2, new Data_Maybe.Nothing()) : new Data_Tuple.Tuple(v_2_i2, new Data_Maybe.Just((((Integer) (i_3_i3)) - ((Integer) (1))))))))).apply((((Integer) (n_1_i1)) - ((Integer) (1))));
public static final Object replicate1A = (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> (java.util.function.Function<Object, Object>) (dictUnfoldable1_1_i1) -> (java.util.function.Function<Object, Object>) (dictTraversable1_2_i2) -> (java.util.function.Function<Object, Object>) (n_3_i3) -> (java.util.function.Function<Object, Object>) (m_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictTraversable1_2_i2).get("sequence1"))).apply(dictApply_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_1_i1).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_5_i5) -> ( ((Boolean) ((((Integer) (i_5_i5)) <= ((Integer) (0))))) ? new Data_Tuple.Tuple(m_4_i4, new Data_Maybe.Nothing()) : new Data_Tuple.Tuple(m_4_i4, new Data_Maybe.Just((((Integer) (i_5_i5)) - ((Integer) (1))))))))).apply((((Integer) (n_3_i3)) - ((Integer) (1)))));
public static final Object singleton = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0_i0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_2_i2) -> ( ((Boolean) ((((Integer) (i_2_i2)) <= ((Integer) (0))))) ? new Data_Tuple.Tuple(v_1_i1, new Data_Maybe.Nothing()) : new Data_Tuple.Tuple(v_1_i1, new Data_Maybe.Just((((Integer) (i_2_i2)) - ((Integer) (1))))))))).apply(0);
public static final Object range = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0_i0) -> (java.util.function.Function<Object, Object>) (start_1_i1) -> (java.util.function.Function<Object, Object>) (end_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0_i0).get("unfoldr1"))).apply(((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = ( ((Boolean) ((((Integer) (end_2_i2)) >= ((Integer) (start_1_i1))))) ? 1 : -1); return (java.util.function.Function<Object, Object>) (i_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object i_prime__5_i5 = (((Integer) (i_4_i4)) + ((Integer) (__local_var_3_i3))); return new Data_Tuple.Tuple(i_4_i4, ( ((Boolean) ((((Integer) (i_4_i4)) == ((Integer) (end_2_i2))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(i_prime__5_i5))); }).get(); }).get()))).apply(start_1_i1);
public static final Object iterateN = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0_i0) -> (java.util.function.Function<Object, Object>) (n_1_i1) -> (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (s_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0_i0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (v_4_i4) -> new Data_Tuple.Tuple((((Data_Tuple.Tuple) v_4_i4).value0), ( ((Boolean) ((((Integer) ((((Data_Tuple.Tuple) v_4_i4).value1))) > ((Integer) (0))))) ? new Data_Maybe.Just(new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_2_i2)).apply((((Data_Tuple.Tuple) v_4_i4).value0)), (((Integer) ((((Data_Tuple.Tuple) v_4_i4).value1))) - ((Integer) (1))))) : new Data_Maybe.Nothing()))))).apply(new Data_Tuple.Tuple(s_3_i3, (((Integer) (n_1_i1)) - ((Integer) (1)))));
}
