public class Data_Profunctor_Strong {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object strongFn = new java.util.LinkedHashMap<String, Object>() {{ put("first", (java.util.function.Function<Object, Object>) (a2b_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (a2b_0_i0)).apply((((Data_Tuple.Tuple) v_1_i1).value0)), (((Data_Tuple.Tuple) v_1_i1).value1))); put("second", (java.util.function.Function<Object, Object>) (f_0_i2) -> (java.util.function.Function<Object, Object>) (m_1_i3) -> new Data_Tuple.Tuple((((Data_Tuple.Tuple) m_1_i3).value0), ((java.util.function.Function<Object, Object>) (f_0_i2)).apply((((Data_Tuple.Tuple) m_1_i3).value1)))); put("Profunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i4) -> Data_Profunctor.profunctorFn); }};
public static final Object second = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("second");
public static final Object first = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("first");
public static final Object splitStrong = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0_i0) -> (java.util.function.Function<Object, Object>) (dictStrong_1_i1) -> (java.util.function.Function<Object, Object>) (l_2_i2) -> (java.util.function.Function<Object, Object>) (r_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0_i0).get("compose"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1_i1).get("second"))).apply(r_3_i3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1_i1).get("first"))).apply(l_2_i2));
public static final Object fanout = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0_i0) -> (java.util.function.Function<Object, Object>) (dictStrong_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object Profunctor0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1_i1).get("Profunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (l_3_i3) -> (java.util.function.Function<Object, Object>) (r_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Profunctor0_2_i2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (a_5_i5) -> new Data_Tuple.Tuple(a_5_i5, a_5_i5)))).apply((java.util.function.Function<Object, Object>) (x_5_i6) -> x_5_i6))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0_i0).get("compose"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1_i1).get("second"))).apply(r_4_i4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1_i1).get("first"))).apply(l_3_i3))); }).get();
}
