public class Data_Bifunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object bimap = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("bimap");
public static final Object bivoid = (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (v_1_i1) -> Data_Unit.unit))).apply((java.util.function.Function<Object, Object>) (v_1_i2) -> Data_Unit.unit);
public static final Object lmap = (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply(f_1_i1))).apply((java.util.function.Function<Object, Object>) (x_2_i2) -> x_2_i2);
public static final Object rmap = (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (x_1_i1) -> x_1_i1);
public static final Object bifunctorTuple = new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (g_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_0_i0)).apply((((Data_Tuple.Tuple) v_2_i2).value0)), ((java.util.function.Function<Object, Object>) (g_1_i1)).apply((((Data_Tuple.Tuple) v_2_i2).value1)))); }};
public static final Object bifunctorEither = new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (v2_2_i2) -> ( ((Boolean) ((v2_2_i2 instanceof Data_Either.Left))) ? new Data_Either.Left(((java.util.function.Function<Object, Object>) (v_0_i0)).apply((((Data_Either.Left) v2_2_i2).value0))) : ( ((Boolean) ((v2_2_i2 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (v1_1_i1)).apply((((Data_Either.Right) v2_2_i2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object bifunctorConst = new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v1_2_i2)); }};
}
