public class Data_Predicate {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Predicate = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object newtypePredicate = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object heytingAlgebraPredicate = new java.util.LinkedHashMap<String, Object>() {{ put("ff", (java.util.function.Function<Object, Object>) (v_0_i0) -> false); put("tt", (java.util.function.Function<Object, Object>) (v_0_i1) -> true); put("implies", (java.util.function.Function<Object, Object>) (f_0_i2) -> (java.util.function.Function<Object, Object>) (g_1_i3) -> (java.util.function.Function<Object, Object>) (a_2_i4) -> (((Boolean) (!(((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i2)).apply(a_2_i4)))))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1_i3)).apply(a_2_i4))))); put("conj", (java.util.function.Function<Object, Object>) (f_0_i5) -> (java.util.function.Function<Object, Object>) (g_1_i6) -> (java.util.function.Function<Object, Object>) (a_2_i7) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i5)).apply(a_2_i7))) && ((Boolean) (((java.util.function.Function<Object, Object>) (g_1_i6)).apply(a_2_i7))))); put("disj", (java.util.function.Function<Object, Object>) (f_0_i8) -> (java.util.function.Function<Object, Object>) (g_1_i9) -> (java.util.function.Function<Object, Object>) (a_2_i10) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i8)).apply(a_2_i10))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1_i9)).apply(a_2_i10))))); put("not", (java.util.function.Function<Object, Object>) (f_0_i11) -> (java.util.function.Function<Object, Object>) (a_1_i12) -> !(((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i11)).apply(a_1_i12))))); }};
public static final Object contravariantPredicate = new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (v_1_i1)).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_2_i2))); }};
public static final Object booleanAlgebraPredicate = ((java.util.function.Supplier<Object>) () -> { Object heytingAlgebraFunction_0_i13 = new java.util.LinkedHashMap<String, Object>() {{ put("ff", (java.util.function.Function<Object, Object>) (v_0_i0) -> false); put("tt", (java.util.function.Function<Object, Object>) (v_0_i1) -> true); put("implies", (java.util.function.Function<Object, Object>) (f_0_i2) -> (java.util.function.Function<Object, Object>) (g_1_i3) -> (java.util.function.Function<Object, Object>) (a_2_i4) -> (((Boolean) (!(((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i2)).apply(a_2_i4)))))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1_i3)).apply(a_2_i4))))); put("conj", (java.util.function.Function<Object, Object>) (f_0_i5) -> (java.util.function.Function<Object, Object>) (g_1_i6) -> (java.util.function.Function<Object, Object>) (a_2_i7) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i5)).apply(a_2_i7))) && ((Boolean) (((java.util.function.Function<Object, Object>) (g_1_i6)).apply(a_2_i7))))); put("disj", (java.util.function.Function<Object, Object>) (f_0_i8) -> (java.util.function.Function<Object, Object>) (g_1_i9) -> (java.util.function.Function<Object, Object>) (a_2_i10) -> (((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i8)).apply(a_2_i10))) || ((Boolean) (((java.util.function.Function<Object, Object>) (g_1_i9)).apply(a_2_i10))))); put("not", (java.util.function.Function<Object, Object>) (f_0_i11) -> (java.util.function.Function<Object, Object>) (a_1_i12) -> !(((Boolean) (((java.util.function.Function<Object, Object>) (f_0_i11)).apply(a_1_i12))))); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_1_i14) -> heytingAlgebraFunction_0_i13); }}; }).get();
}
