public class Data_Semiring_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object genericZeroprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericZero'");
public static final Object genericZero = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemiring_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("to"))).apply(((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_1_i1).get("genericZero'"));
public static final Object genericSemiringNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericAdd'", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Generic_Rep.NoArguments()); put("genericZero'", new Data_Generic_Rep.NoArguments()); put("genericMul'", (java.util.function.Function<Object, Object>) (v_0_i2) -> (java.util.function.Function<Object, Object>) (v1_1_i3) -> new Data_Generic_Rep.NoArguments()); put("genericOne'", new Data_Generic_Rep.NoArguments()); }};
public static final Object genericSemiringArgument = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericAdd'", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("add"))).apply(v_1_i1))).apply(v1_2_i2)); put("genericZero'", ((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("zero")); put("genericMul'", (java.util.function.Function<Object, Object>) (v_1_i3) -> (java.util.function.Function<Object, Object>) (v1_2_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("mul"))).apply(v_1_i3))).apply(v1_2_i4)); put("genericOne'", ((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("one")); }};
public static final Object genericOneprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericOne'");
public static final Object genericOne = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemiring_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("to"))).apply(((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_1_i1).get("genericOne'"));
public static final Object genericMulprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericMul'");
public static final Object genericMul = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemiring_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("to"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_1_i1).get("genericMul'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(y_3_i3)));
public static final Object genericAddprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericAdd'");
public static final Object genericSemiringConstructor = (java.util.function.Function<Object, Object>) (dictGenericSemiring_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericAdd'", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericAdd'"))).apply(v_1_i1))).apply(v1_2_i2)); put("genericZero'", ((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericZero'")); put("genericMul'", (java.util.function.Function<Object, Object>) (v_1_i3) -> (java.util.function.Function<Object, Object>) (v1_2_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericMul'"))).apply(v_1_i3))).apply(v1_2_i4)); put("genericOne'", ((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericOne'")); }};
public static final Object genericSemiringProduct = (java.util.function.Function<Object, Object>) (dictGenericSemiring_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemiring1_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericAdd'", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericAdd'"))).apply((((Data_Generic_Rep.Product) v_2_i2).value0)))).apply((((Data_Generic_Rep.Product) v1_3_i3).value0)), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring1_1_i1).get("genericAdd'"))).apply((((Data_Generic_Rep.Product) v_2_i2).value1)))).apply((((Data_Generic_Rep.Product) v1_3_i3).value1)))); put("genericZero'", new Data_Generic_Rep.Product(((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericZero'"), ((java.util.LinkedHashMap<String, Object>) dictGenericSemiring1_1_i1).get("genericZero'"))); put("genericMul'", (java.util.function.Function<Object, Object>) (v_2_i4) -> (java.util.function.Function<Object, Object>) (v1_3_i5) -> new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericMul'"))).apply((((Data_Generic_Rep.Product) v_2_i4).value0)))).apply((((Data_Generic_Rep.Product) v1_3_i5).value0)), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring1_1_i1).get("genericMul'"))).apply((((Data_Generic_Rep.Product) v_2_i4).value1)))).apply((((Data_Generic_Rep.Product) v1_3_i5).value1)))); put("genericOne'", new Data_Generic_Rep.Product(((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_0_i0).get("genericOne'"), ((java.util.LinkedHashMap<String, Object>) dictGenericSemiring1_1_i1).get("genericOne'"))); }};
public static final Object genericAdd = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemiring_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("to"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemiring_1_i1).get("genericAdd'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(y_3_i3)));
}
