public class Data_Monoid_Additive {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Additive = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showAdditive = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Additive ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object semigroupAdditive = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("add"))).apply(v_1_i1))).apply(v1_2_i2)); }};
public static final Object ordAdditive = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> dictOrd_0_i0;
public static final Object monoidAdditive = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupAdditive1_1_i3 = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("add"))).apply(v_1_i1))).apply(v1_2_i2)); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.LinkedHashMap<String, Object>) dictSemiring_0_i0).get("zero")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> semigroupAdditive1_1_i3); }}; }).get();
public static final Object functorAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (m_1_i1) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(m_1_i1)); }};
public static final Object eqAdditive = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object eq1Additive = new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq")); }};
public static final Object ord1Additive = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare")); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Monoid_Additive.eq1Additive); }};
public static final Object boundedAdditive = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> dictBounded_0_i0;
public static final Object applyAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ((java.util.function.Function<Object, Object>) (v_0_i0)).apply(v1_1_i1)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Monoid_Additive.functorAdditive); }};
public static final Object bindAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(v_0_i0)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Monoid_Additive.applyAdditive); }};
public static final Object applicativeAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Monoid_Additive.applyAdditive); }};
public static final Object monadAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Monoid_Additive.applicativeAdditive); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Monoid_Additive.bindAdditive); }};
}
