public class Data_Monoid_Conj {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Conj = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showConj = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Conj ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object semiringConj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("zero", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("tt")); put("one", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("ff")); put("add", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("conj"))).apply(v_1_i1))).apply(v1_2_i2)); put("mul", (java.util.function.Function<Object, Object>) (v_1_i3) -> (java.util.function.Function<Object, Object>) (v1_2_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("disj"))).apply(v_1_i3))).apply(v1_2_i4)); }};
public static final Object semigroupConj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("conj"))).apply(v_1_i1))).apply(v1_2_i2)); }};
public static final Object ordConj = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> dictOrd_0_i0;
public static final Object monoidConj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupConj1_1_i3 = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("conj"))).apply(v_1_i1))).apply(v1_2_i2)); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0_i0).get("tt")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> semigroupConj1_1_i3); }}; }).get();
public static final Object functorConj = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (m_1_i1) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(m_1_i1)); }};
public static final Object eqConj = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object eq1Conj = new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq")); }};
public static final Object ord1Conj = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare")); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Monoid_Conj.eq1Conj); }};
public static final Object boundedConj = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> dictBounded_0_i0;
public static final Object applyConj = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ((java.util.function.Function<Object, Object>) (v_0_i0)).apply(v1_1_i1)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Monoid_Conj.functorConj); }};
public static final Object bindConj = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(v_0_i0)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Monoid_Conj.applyConj); }};
public static final Object applicativeConj = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Monoid_Conj.applyConj); }};
public static final Object monadConj = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Monoid_Conj.applicativeConj); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Monoid_Conj.bindConj); }};
}
