public class Data_Traversable_Accum_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object StateR = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object StateL = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object stateR = (java.util.function.Function<Object, Object>) (v_0_i0) -> v_0_i0;
public static final Object stateL = (java.util.function.Function<Object, Object>) (v_0_i0) -> v_0_i0;
public static final Object functorStateR = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (k_1_i1) -> (java.util.function.Function<Object, Object>) (s_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (k_1_i1)).apply(s_2_i2); return new java.util.LinkedHashMap<String, Object>() {{ put("accum", ((java.util.LinkedHashMap<String, Object>) v_3_i3).get("accum")); put("value", ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(((java.util.LinkedHashMap<String, Object>) v_3_i3).get("value"))); }}; }).get()); }};
public static final Object functorStateL = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (k_1_i1) -> (java.util.function.Function<Object, Object>) (s_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (k_1_i1)).apply(s_2_i2); return new java.util.LinkedHashMap<String, Object>() {{ put("accum", ((java.util.LinkedHashMap<String, Object>) v_3_i3).get("accum")); put("value", ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(((java.util.LinkedHashMap<String, Object>) v_3_i3).get("value"))); }}; }).get()); }};
public static final Object applyStateR = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (s_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (x_1_i1)).apply(s_2_i2); return ((java.util.function.Supplier<Object>) () -> { Object v1_4_i4 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(((java.util.LinkedHashMap<String, Object>) v_3_i3).get("accum")); return new java.util.LinkedHashMap<String, Object>() {{ put("accum", ((java.util.LinkedHashMap<String, Object>) v1_4_i4).get("accum")); put("value", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) v1_4_i4).get("value"))).apply(((java.util.LinkedHashMap<String, Object>) v_3_i3).get("value"))); }}; }).get(); }).get()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i5) -> Data_Traversable_Accum_Internal.functorStateR); }};
public static final Object applyStateL = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (s_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(s_2_i2); return ((java.util.function.Supplier<Object>) () -> { Object v1_4_i4 = ((java.util.function.Function<Object, Object>) (x_1_i1)).apply(((java.util.LinkedHashMap<String, Object>) v_3_i3).get("accum")); return new java.util.LinkedHashMap<String, Object>() {{ put("accum", ((java.util.LinkedHashMap<String, Object>) v1_4_i4).get("accum")); put("value", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) v_3_i3).get("value"))).apply(((java.util.LinkedHashMap<String, Object>) v1_4_i4).get("value"))); }}; }).get(); }).get()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i5) -> Data_Traversable_Accum_Internal.functorStateL); }};
public static final Object applicativeStateR = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (s_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("accum", s_1_i1); put("value", a_0_i0); }}); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Traversable_Accum_Internal.applyStateR); }};
public static final Object applicativeStateL = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (s_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("accum", s_1_i1); put("value", a_0_i0); }}); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Traversable_Accum_Internal.applyStateL); }};
}
