public class Data_Functor_App {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object App = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showApp = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(App ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object semigroupApp = (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> (java.util.function.Function<Object, Object>) (dictSemigroup_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object append_2_i2 = ((java.util.LinkedHashMap<String, Object>) dictSemigroup_1_i1).get("append"); return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_3_i3) -> (java.util.function.Function<Object, Object>) (v1_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0_i0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(append_2_i2))).apply(v_3_i3)))).apply(v1_4_i4)); }}; }).get();
public static final Object plusApp = (java.util.function.Function<Object, Object>) (dictPlus_0_i0) -> dictPlus_0_i0;
public static final Object newtypeApp = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidApp = (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0_i0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictMonoid_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupApp2_3_i6 = ((java.util.function.Supplier<Object>) () -> { Object append_3_i3 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_2_i2).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)).get("append"); return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_4_i4) -> (java.util.function.Function<Object, Object>) (v1_5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(append_3_i3))).apply(v_4_i4)))).apply(v1_5_i5)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0_i0).get("pure"))).apply(((java.util.LinkedHashMap<String, Object>) dictMonoid_2_i2).get("mempty"))); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_4_i7) -> semigroupApp2_3_i6); }}; }).get(); }).get();
public static final Object monadPlusApp = (java.util.function.Function<Object, Object>) (dictMonadPlus_0_i0) -> dictMonadPlus_0_i0;
public static final Object monadApp = (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> dictMonad_0_i0;
public static final Object lazyApp = (java.util.function.Function<Object, Object>) (dictLazy_0_i0) -> dictLazy_0_i0;
public static final Object hoistLowerApp = Unsafe_Coerce.unsafeCoerce;
public static final Object hoistLiftApp = Unsafe_Coerce.unsafeCoerce;
public static final Object hoistApp = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v_1_i1);
public static final Object functorApp = (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> dictFunctor_0_i0;
public static final Object extendApp = (java.util.function.Function<Object, Object>) (dictExtend_0_i0) -> dictExtend_0_i0;
public static final Object eqApp = (java.util.function.Function<Object, Object>) (dictEq1_0_i0) -> (java.util.function.Function<Object, Object>) (dictEq_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq1_0_i0).get("eq1"))).apply(dictEq_1_i1))).apply(x_2_i2))).apply(y_3_i3)); }};
public static final Object ordApp = (java.util.function.Function<Object, Object>) (dictOrd1_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0_i0).get("Eq10"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictOrd_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object eqApp2_3_i6 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_2_i2).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_4_i4) -> (java.util.function.Function<Object, Object>) (y_5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("eq1"))).apply(__local_var_3_i3))).apply(x_4_i4))).apply(y_5_i5)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_4_i7) -> (java.util.function.Function<Object, Object>) (y_5_i8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0_i0).get("compare1"))).apply(dictOrd_2_i2))).apply(x_4_i7))).apply(y_5_i8)); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_4_i9) -> eqApp2_3_i6); }}; }).get(); }).get();
public static final Object eq1App = (java.util.function.Function<Object, Object>) (dictEq1_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq1_0_i0).get("eq1"))).apply(dictEq_1_i1))).apply(x_2_i2))).apply(y_3_i3)); }};
public static final Object ord1App = (java.util.function.Function<Object, Object>) (dictOrd1_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eq1App1_1_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0_i0).get("Eq10"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> (java.util.function.Function<Object, Object>) (y_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("eq1"))).apply(dictEq_2_i2))).apply(x_3_i3))).apply(y_4_i4)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_2_i6) -> (java.util.function.Function<Object, Object>) (x_3_i7) -> (java.util.function.Function<Object, Object>) (y_4_i8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0_i0).get("compare1"))).apply(dictOrd_2_i6))).apply(x_3_i7))).apply(y_4_i8)); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i9) -> eq1App1_1_i5); }}; }).get();
public static final Object comonadApp = (java.util.function.Function<Object, Object>) (dictComonad_0_i0) -> dictComonad_0_i0;
public static final Object bindApp = (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> dictBind_0_i0;
public static final Object applyApp = (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> dictApply_0_i0;
public static final Object applicativeApp = (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> dictApplicative_0_i0;
public static final Object alternativeApp = (java.util.function.Function<Object, Object>) (dictAlternative_0_i0) -> dictAlternative_0_i0;
public static final Object altApp = (java.util.function.Function<Object, Object>) (dictAlt_0_i0) -> dictAlt_0_i0;
}
