public class Data_Ring_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object genericSubprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericSub'");
public static final Object genericSub = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericRing_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("to"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericRing_1_i1).get("genericSub'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(y_3_i3)));
public static final Object genericRingProduct = (java.util.function.Function<Object, Object>) (dictGenericRing_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericRing1_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericSub'", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericRing_0_i0).get("genericSub'"))).apply((((Data_Generic_Rep.Product) v_2_i2).value0)))).apply((((Data_Generic_Rep.Product) v1_3_i3).value0)), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericRing1_1_i1).get("genericSub'"))).apply((((Data_Generic_Rep.Product) v_2_i2).value1)))).apply((((Data_Generic_Rep.Product) v1_3_i3).value1)))); }};
public static final Object genericRingNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericSub'", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Generic_Rep.NoArguments()); }};
public static final Object genericRingConstructor = (java.util.function.Function<Object, Object>) (dictGenericRing_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericSub'", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericRing_0_i0).get("genericSub'"))).apply(v_1_i1))).apply(v1_2_i2)); }};
public static final Object genericRingArgument = (java.util.function.Function<Object, Object>) (dictRing_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericSub'", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_0_i0).get("sub"))).apply(v_1_i1))).apply(v1_2_i2)); }};
}
