public class Data_Functor_Product_Nested {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object product9 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> (java.util.function.Function<Object, Object>) (e_4_i4) -> (java.util.function.Function<Object, Object>) (f_5_i5) -> (java.util.function.Function<Object, Object>) (g_6_i6) -> (java.util.function.Function<Object, Object>) (h_7_i7) -> (java.util.function.Function<Object, Object>) (i_8_i8) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, new Data_Tuple.Tuple(e_4_i4, new Data_Tuple.Tuple(f_5_i5, new Data_Tuple.Tuple(g_6_i6, new Data_Tuple.Tuple(h_7_i7, new Data_Tuple.Tuple(i_8_i8, Data_Unit.unit)))))))));
public static final Object product8 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> (java.util.function.Function<Object, Object>) (e_4_i4) -> (java.util.function.Function<Object, Object>) (f_5_i5) -> (java.util.function.Function<Object, Object>) (g_6_i6) -> (java.util.function.Function<Object, Object>) (h_7_i7) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, new Data_Tuple.Tuple(e_4_i4, new Data_Tuple.Tuple(f_5_i5, new Data_Tuple.Tuple(g_6_i6, new Data_Tuple.Tuple(h_7_i7, Data_Unit.unit))))))));
public static final Object product7 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> (java.util.function.Function<Object, Object>) (e_4_i4) -> (java.util.function.Function<Object, Object>) (f_5_i5) -> (java.util.function.Function<Object, Object>) (g_6_i6) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, new Data_Tuple.Tuple(e_4_i4, new Data_Tuple.Tuple(f_5_i5, new Data_Tuple.Tuple(g_6_i6, Data_Unit.unit)))))));
public static final Object product6 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> (java.util.function.Function<Object, Object>) (e_4_i4) -> (java.util.function.Function<Object, Object>) (f_5_i5) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, new Data_Tuple.Tuple(e_4_i4, new Data_Tuple.Tuple(f_5_i5, Data_Unit.unit))))));
public static final Object product5 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> (java.util.function.Function<Object, Object>) (e_4_i4) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, new Data_Tuple.Tuple(e_4_i4, Data_Unit.unit)))));
public static final Object product4 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, Data_Unit.unit))));
public static final Object product3 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, Data_Unit.unit)));
public static final Object product2 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, Data_Unit.unit));
public static final Object product10 = (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> (java.util.function.Function<Object, Object>) (c_2_i2) -> (java.util.function.Function<Object, Object>) (d_3_i3) -> (java.util.function.Function<Object, Object>) (e_4_i4) -> (java.util.function.Function<Object, Object>) (f_5_i5) -> (java.util.function.Function<Object, Object>) (g_6_i6) -> (java.util.function.Function<Object, Object>) (h_7_i7) -> (java.util.function.Function<Object, Object>) (i_8_i8) -> (java.util.function.Function<Object, Object>) (j_9_i9) -> new Data_Tuple.Tuple(a_0_i0, new Data_Tuple.Tuple(b_1_i1, new Data_Tuple.Tuple(c_2_i2, new Data_Tuple.Tuple(d_3_i3, new Data_Tuple.Tuple(e_4_i4, new Data_Tuple.Tuple(f_5_i5, new Data_Tuple.Tuple(g_6_i6, new Data_Tuple.Tuple(h_7_i7, new Data_Tuple.Tuple(i_8_i8, new Data_Tuple.Tuple(j_9_i9, Data_Unit.unit))))))))));
public static final Object product1 = (java.util.function.Function<Object, Object>) (a_0_i0) -> new Data_Tuple.Tuple(a_0_i0, Data_Unit.unit);
public static final Object get9 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get8 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get7 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get6 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get5 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value1)).value0);
public static final Object get4 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value0);
public static final Object get3 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value0);
public static final Object get2 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value0);
public static final Object get10 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0_i0).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get1 = (java.util.function.Function<Object, Object>) (v_0_i0) -> (((Data_Tuple.Tuple) v_0_i0).value0);
}
