public class Data_Number_Approximate {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Tolerance = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object Fraction = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object eqRelative = (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (v2_2_i2) -> ( ((Boolean) (java.util.Objects.equals(v1_1_i1, 0.0))) ? !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply(v2_2_i2)))).apply(v_0_i0) instanceof Data_Ordering.GT)))) : ( ((Boolean) (java.util.Objects.equals(v2_2_i2, 0.0))) ? !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply(v1_1_i1)))).apply(v_0_i0) instanceof Data_Ordering.GT)))) : !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply((((Double) (v1_1_i1)) - ((Double) (v2_2_i2))))))).apply((((Double) ((((Double) (v_0_i0)) * ((Double) (((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply((((Double) (v1_1_i1)) + ((Double) (v2_2_i2))))))))) / ((Double) (2.0)))) instanceof Data_Ordering.GT))))));
public static final Object eqApproximate = ((java.util.function.Function<Object, Object>) (Data_Number_Approximate.eqRelative)).apply(0.000001);
public static final Object neqApproximate = (java.util.function.Function<Object, Object>) (x_0_i0) -> (java.util.function.Function<Object, Object>) (y_1_i1) -> !(((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Number_Approximate.eqRelative)).apply(0.000001))).apply(x_0_i0))).apply(y_1_i1))));
public static final Object eqAbsolute = (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply((((Double) (x_1_i1)) - ((Double) (y_2_i2))))))).apply(v_0_i0) instanceof Data_Ordering.GT))));
}
