public class Data_Functor_Clown {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Clown = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showClown = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Clown ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object profunctorClown = (java.util.function.Function<Object, Object>) (dictContravariant_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("dimap", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictContravariant_0_i0).get("cmap"))).apply(f_1_i1))).apply(v1_3_i3)); }};
public static final Object ordClown = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> dictOrd_0_i0;
public static final Object newtypeClown = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object hoistClown = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v_1_i1);
public static final Object functorClown = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> v1_1_i1); }};
public static final Object eqClown = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object bifunctorClown = (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0_i0).get("map"))).apply(f_1_i1))).apply(v1_3_i3)); }};
public static final Object biapplyClown = (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object bifunctorClown1_1_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (v_3_i3) -> (java.util.function.Function<Object, Object>) (v1_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("map"))).apply(f_2_i2))).apply(v1_4_i4)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_2_i6) -> (java.util.function.Function<Object, Object>) (v1_3_i7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0_i0).get("apply"))).apply(v_2_i6))).apply(v1_3_i7)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i8) -> bifunctorClown1_1_i5); }}; }).get();
public static final Object biapplicativeClown = (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object biapplyClown1_1_i10 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0_i0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object bifunctorClown1_2_i6 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_3_i3) -> (java.util.function.Function<Object, Object>) (v_4_i4) -> (java.util.function.Function<Object, Object>) (v1_5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2_i2).get("map"))).apply(f_3_i3))).apply(v1_5_i5)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_3_i7) -> (java.util.function.Function<Object, Object>) (v1_4_i8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("apply"))).apply(v_3_i7))).apply(v1_4_i8)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i9) -> bifunctorClown1_2_i6); }}; }).get(); }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("bipure", (java.util.function.Function<Object, Object>) (a_2_i11) -> (java.util.function.Function<Object, Object>) (v_3_i12) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0_i0).get("pure"))).apply(a_2_i11)); put("Biapply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i13) -> biapplyClown1_1_i10); }}; }).get();
}
