public class Data_Profunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object profunctorFn = new java.util.LinkedHashMap<String, Object>() {{ put("dimap", (java.util.function.Function<Object, Object>) (a2b_0_i0) -> (java.util.function.Function<Object, Object>) (c2d_1_i1) -> (java.util.function.Function<Object, Object>) (b2c_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> ((java.util.function.Function<Object, Object>) (c2d_1_i1)).apply(((java.util.function.Function<Object, Object>) (b2c_2_i2)).apply(((java.util.function.Function<Object, Object>) (a2b_0_i0)).apply(x_3_i3)))); }};
public static final Object dimap = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("dimap");
public static final Object lcmap = (java.util.function.Function<Object, Object>) (dictProfunctor_0_i0) -> (java.util.function.Function<Object, Object>) (a2b_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0_i0).get("dimap"))).apply(a2b_1_i1))).apply((java.util.function.Function<Object, Object>) (x_2_i2) -> x_2_i2);
public static final Object rmap = (java.util.function.Function<Object, Object>) (dictProfunctor_0_i0) -> (java.util.function.Function<Object, Object>) (b2c_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0_i0).get("dimap"))).apply((java.util.function.Function<Object, Object>) (x_2_i2) -> x_2_i2))).apply(b2c_1_i1);
public static final Object unwrapIso = (java.util.function.Function<Object, Object>) (dictProfunctor_0_i0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0_i0).get("dimap"))).apply(Unsafe_Coerce.unsafeCoerce))).apply(Unsafe_Coerce.unsafeCoerce);
public static final Object wrapIso = (java.util.function.Function<Object, Object>) (dictProfunctor_0_i0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0_i0).get("dimap"))).apply(Unsafe_Coerce.unsafeCoerce))).apply(Unsafe_Coerce.unsafeCoerce);
public static final Object arr = (java.util.function.Function<Object, Object>) (dictCategory_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object identity2_1_i1 = ((java.util.LinkedHashMap<String, Object>) dictCategory_0_i0).get("identity"); return (java.util.function.Function<Object, Object>) (dictProfunctor_2_i2) -> (java.util.function.Function<Object, Object>) (f_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_2_i2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (x_4_i4) -> x_4_i4))).apply(f_3_i3))).apply(identity2_1_i1); }).get();
}
