public class Data_Semigroup {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object concatArray = FFI_STUB;
    public static Object concatArray(Object... args) { return null; }
    public static Object concatString = FFI_STUB;
    public static Object concatString(Object... args) { return null; }

public static final Object semigroupVoid = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0_i0) -> Data_Void.absurd); }};
public static final Object semigroupUnit = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> Data_Unit.unit); }};
public static final Object semigroupString = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Function<Object, Object>) (b) -> a.toString() + b.toString()); }};
public static final Object semigroupRecordNil = new java.util.LinkedHashMap<String, Object>() {{ put("appendRecord", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> (java.util.function.Function<Object, Object>) (v2_2_i2) -> new java.util.LinkedHashMap<String, Object>() {{ }}); }};
public static final Object semigroupProxy = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Type_Proxy.Proxy()); }};
public static final Object semigroupArray = new java.util.LinkedHashMap<String, Object>() {{ put("append", Data_Semigroup.concatArray); }};
public static final Object appendRecord = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("appendRecord");
public static final Object semigroupRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> (java.util.function.Function<Object, Object>) (dictSemigroupRecord_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupRecord_1_i1).get("appendRecord"))).apply(new Type_Proxy.Proxy())); }};
public static final Object append = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("append");
public static final Object semigroupFn = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(x_3_i3)))).apply(((java.util.function.Function<Object, Object>) (g_2_i2)).apply(x_3_i3))); }};
public static final Object semigroupRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0_i0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1_i1) -> (java.util.function.Function<Object, Object>) (dictSemigroupRecord_2_i2) -> (java.util.function.Function<Object, Object>) (dictSemigroup_3_i3) -> new java.util.LinkedHashMap<String, Object>() {{ put("appendRecord", (java.util.function.Function<Object, Object>) (v_4_i4) -> (java.util.function.Function<Object, Object>) (ra_5_i5) -> (java.util.function.Function<Object, Object>) (rb_6_i6) -> ((java.util.function.Supplier<Object>) () -> { Object key_7_i7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0_i0).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); return ((java.util.function.Supplier<Object>) () -> { Object get_8_i8 = ((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_7_i7); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(key_7_i7))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_3_i3).get("append"))).apply(((java.util.function.Function<Object, Object>) (get_8_i8)).apply(ra_5_i5)))).apply(((java.util.function.Function<Object, Object>) (get_8_i8)).apply(rb_6_i6))))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupRecord_2_i2).get("appendRecord"))).apply(new Type_Proxy.Proxy()))).apply(ra_5_i5))).apply(rb_6_i6)); }).get(); }).get()); }};
}
