public class Data_Array_ST_Iterator {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Iterator {
            public final Object value0;
            public final Object value1;
            public Iterator(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Iterator = (java.util.function.Function<Object, Object>) (value0_i0) -> (java.util.function.Function<Object, Object>) (value1_i0) -> new Data_Array_ST_Iterator.Iterator(value0_i0, value1_i0);
public static final Object peek = (java.util.function.Function<Object, Object>) (v_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = (((Data_Array_ST_Iterator.Iterator) v_0_i0).value1); return ((java.util.function.Supplier<Object>) () -> { Object i_2_i2 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) v_0_i0).value0))).apply(i_2_i2); }).get(); }).get();
public static final Object next = (java.util.function.Function<Object, Object>) (v_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = (((Data_Array_ST_Iterator.Iterator) v_0_i0).value1); return ((java.util.function.Supplier<Object>) () -> { Object i_2_i2 = null /* TODO: PrimEffect */; return ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = null /* TODO: PrimEffect */; return ((java.util.function.Supplier<Object>) () -> { Object _dollar___unused_4_i4 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) v_0_i0).value0))).apply(i_2_i2); }).get(); }).get(); }).get(); }).get();
public static final Object pushWhile = (java.util.function.Function<Object, Object>) (p_0_i0) -> (java.util.function.Function<Object, Object>) (iter_1_i1) -> (java.util.function.Function<Object, Object>) (array_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object go__break_3_i3 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i4 = null /* TODO: PrimEffect */; return !(((Boolean) (__local_var_4_i4))); }).get()))).apply(((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i5 = (((Data_Array_ST_Iterator.Iterator) iter_1_i1).value1); return ((java.util.function.Supplier<Object>) () -> { Object mx_5_i7 = ((java.util.function.Supplier<Object>) () -> { Object i_5_i6 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) iter_1_i1).value0))).apply(i_5_i6); }).get(); return ( ((Boolean) ((((Boolean) ((mx_5_i7 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (p_0_i0)).apply((((Data_Maybe.Just) mx_5_i7).value0))))))) ? ((java.util.function.Supplier<Object>) () -> { Object _dollar___unused_6_i8 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_ST.pushImpl)).apply((((Data_Maybe.Just) mx_5_i7).value0)))).apply(array_2_i2); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_7_i12 = ((java.util.function.Supplier<Object>) () -> { Object i_7_i9 = null /* TODO: PrimEffect */; return ((java.util.function.Supplier<Object>) () -> { Object __local_var_8_i10 = null /* TODO: PrimEffect */; return ((java.util.function.Supplier<Object>) () -> { Object _dollar___unused_9_i11 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) iter_1_i1).value0))).apply(i_7_i9); }).get(); }).get(); }).get(); return Data_Unit.unit; }).get(); }).get() : ((java.util.function.Supplier<Object>) () -> { Object __local_var_6_i13 = null /* TODO: PrimEffect */; return Data_Unit.unit; }).get()); }).get(); }).get()); }).get();
public static final Object pushAll = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.pushWhile)).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> true);
public static final Object iterator = (java.util.function.Function<Object, Object>) (f_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.Iterator)).apply(f_0_i0); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(__local_var_2_i2); }).get(); }).get();
public static final Object iterate = (java.util.function.Function<Object, Object>) (iter_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object go__break_2_i2 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = null /* TODO: PrimEffect */; return !(((Boolean) (__local_var_3_i3))); }).get()))).apply(((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i4 = (((Data_Array_ST_Iterator.Iterator) iter_0_i0).value1); return ((java.util.function.Supplier<Object>) () -> { Object mx_4_i8 = ((java.util.function.Supplier<Object>) () -> { Object i_4_i5 = null /* TODO: PrimEffect */; return ((java.util.function.Supplier<Object>) () -> { Object __local_var_5_i6 = null /* TODO: PrimEffect */; return ((java.util.function.Supplier<Object>) () -> { Object _dollar___unused_6_i7 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) iter_0_i0).value0))).apply(i_4_i5); }).get(); }).get(); }).get(); return ( ((Boolean) ((mx_4_i8 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (f_1_i1)).apply((((Data_Maybe.Just) mx_4_i8).value0)) : ( ((Boolean) ((mx_4_i8 instanceof Data_Maybe.Nothing))) ? ((java.util.function.Supplier<Object>) () -> { Object __local_var_5_i9 = null /* TODO: PrimEffect */; return Data_Unit.unit; }).get() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); }).get(); }).get()); }).get();
public static final Object exhausted = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i3 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = (((Data_Array_ST_Iterator.Iterator) x_0_i0).value1); return ((java.util.function.Supplier<Object>) () -> { Object i_2_i2 = null /* TODO: PrimEffect */; return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) x_0_i0).value0))).apply(i_2_i2); }).get(); }).get(); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i4 = __local_var_1_i3; return ( ((Boolean) ((__local_var_2_i4 instanceof Data_Maybe.Nothing))) ? true : ( ((Boolean) ((__local_var_2_i4 instanceof Data_Maybe.Just))) ? false : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); }).get(); }).get();
}
