public class Data_Array_NonEmpty_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object foldl1Impl = FFI_STUB;
    public static Object foldl1Impl(Object... args) { return null; }
    public static Object foldr1Impl = FFI_STUB;
    public static Object foldr1Impl(Object... args) { return null; }
    public static Object traverse1Impl = FFI_STUB;
    public static Object traverse1Impl(Object... args) { return null; }

public static final Object NonEmptyArray = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object unfoldable1NonEmptyArray = Data_Unfoldable1.unfoldable1Array;
public static final Object traversableWithIndexNonEmptyArray = Data_TraversableWithIndex.traversableWithIndexArray;
public static final Object traversableNonEmptyArray = Data_Traversable.traversableArray;
public static final Object showNonEmptyArray = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object showArray_1_i1 = new java.util.LinkedHashMap<String, Object>() {{ put("show", ((java.util.function.Function<Object, Object>) (Data_Show.showArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_2_i2) -> (((String) ((((String) ("(NonEmptyArray ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) showArray_1_i1).get("show"))).apply(v_2_i2)))))) + ((String) (")")))); }}; }).get();
public static final Object semigroupNonEmptyArray = Data_Semigroup.semigroupArray;
public static final Object ordNonEmptyArray = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqArray_1_i1 = new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)).get("eq"))); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (xs_2_i2) -> (java.util.function.Function<Object, Object>) (ys_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_4_i4) -> (java.util.function.Function<Object, Object>) (y_5_i5) -> ((java.util.function.Supplier<Object>) () -> { Object v_6_i6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_4_i4))).apply(y_5_i5); return ( ((Boolean) ((v_6_i6 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_6_i6 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_6_i6 instanceof Data_Ordering.GT))) ? -1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()))).apply(xs_2_i2))).apply(ys_3_i3))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> eqArray_1_i1); }}; }).get();
public static final Object ord1NonEmptyArray = Data_Ord.ord1Array;
public static final Object monadNonEmptyArray = Control_Monad.monadArray;
public static final Object functorWithIndexNonEmptyArray = Data_FunctorWithIndex.functorWithIndexArray;
public static final Object functorNonEmptyArray = Data_Functor.functorArray;
public static final Object foldableWithIndexNonEmptyArray = Data_FoldableWithIndex.foldableWithIndexArray;
public static final Object foldableNonEmptyArray = Data_Foldable.foldableArray;
public static final Object foldable1NonEmptyArray = new java.util.LinkedHashMap<String, Object>() {{ put("foldMap1", (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object append_1_i1 = ((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"); return (java.util.function.Function<Object, Object>) (f_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (Data_Functor.arrayMap)).apply(f_2_i2); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Array_NonEmpty_Internal.foldable1NonEmptyArray).get("foldl1"))).apply(append_1_i1); return (java.util.function.Function<Object, Object>) (x_5_i5) -> ((java.util.function.Function<Object, Object>) (__local_var_4_i4)).apply(((java.util.function.Function<Object, Object>) (__local_var_3_i3)).apply(x_5_i5)); }).get(); }).get(); }).get()); put("foldr1", (java.util.function.Function<Object, Object>) (__local_var_0_i6) -> (java.util.function.Function<Object, Object>) (__local_var_1_i7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.foldr1Impl)).apply(__local_var_0_i6))).apply(__local_var_1_i7)); put("foldl1", (java.util.function.Function<Object, Object>) (__local_var_0_i8) -> (java.util.function.Function<Object, Object>) (__local_var_1_i9) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.foldl1Impl)).apply(__local_var_0_i8))).apply(__local_var_1_i9)); put("Foldable0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i10) -> Data_Foldable.foldableArray); }};
public static final Object traversable1NonEmptyArray = new java.util.LinkedHashMap<String, Object>() {{ put("traverse1", (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object apply_1_i1 = ((java.util.LinkedHashMap<String, Object>) dictApply_0_i0).get("apply"); return ((java.util.function.Supplier<Object>) () -> { Object go__map_2_i2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"); return (java.util.function.Function<Object, Object>) (f_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.traverse1Impl)).apply(apply_1_i1))).apply(go__map_2_i2))).apply(f_3_i3); }).get(); }).get()); put("sequence1", (java.util.function.Function<Object, Object>) (dictApply_0_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Array_NonEmpty_Internal.traversable1NonEmptyArray).get("traverse1"))).apply(dictApply_0_i4))).apply((java.util.function.Function<Object, Object>) (x_1_i5) -> x_1_i5)); put("Foldable10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i6) -> Data_Array_NonEmpty_Internal.foldable1NonEmptyArray); put("Traversable1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i7) -> Data_Traversable.traversableArray); }};
public static final Object eqNonEmptyArray = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq"))); }};
public static final Object eq1NonEmptyArray = Data_Eq.eq1Array;
public static final Object bindNonEmptyArray = Control_Bind.bindArray;
public static final Object applyNonEmptyArray = Control_Apply.applyArray;
public static final Object applicativeNonEmptyArray = Control_Applicative.applicativeArray;
public static final Object altNonEmptyArray = Control_Alt.altArray;
}
