public class Data_Functor_Invariant {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object invariantMultiplicative = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v1_2_i2)); }};
public static final Object invariantEndo = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (ab_0_i0) -> (java.util.function.Function<Object, Object>) (ba_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (x_3_i3) -> ((java.util.function.Function<Object, Object>) (ab_0_i0)).apply(((java.util.function.Function<Object, Object>) (v_2_i2)).apply(((java.util.function.Function<Object, Object>) (ba_1_i1)).apply(x_3_i3)))); }};
public static final Object invariantDual = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v1_2_i2)); }};
public static final Object invariantDisj = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v1_2_i2)); }};
public static final Object invariantConj = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v1_2_i2)); }};
public static final Object invariantAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v1_2_i2)); }};
public static final Object imapF = (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0_i0).get("map"))).apply(f_1_i1);
public static final Object invariantArray = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> ((java.util.function.Function<Object, Object>) (Data_Functor.arrayMap)).apply(f_0_i0)); }};
public static final Object invariantFn = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Semigroupoid.semigroupoidFn).get("compose"))).apply(f_0_i0)); }};
public static final Object imap = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("imap");
public static final Object invariantAlternate = (java.util.function.Function<Object, Object>) (dictInvariant_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (v_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictInvariant_0_i0).get("imap"))).apply(f_1_i1))).apply(g_2_i2))).apply(v_3_i3)); }};
}
