public class Data_DivisionRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object recip = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("recip");
public static final Object rightDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Semiring0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0_i0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2_i2) -> (java.util.function.Function<Object, Object>) (b_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Semiring0_1_i1).get("mul"))).apply(a_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0_i0).get("recip"))).apply(b_3_i3)); }).get();
public static final Object leftDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Semiring0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0_i0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2_i2) -> (java.util.function.Function<Object, Object>) (b_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Semiring0_1_i1).get("mul"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0_i0).get("recip"))).apply(b_3_i3)))).apply(a_2_i2); }).get();
public static final Object divisionringNumber = new java.util.LinkedHashMap<String, Object>() {{ put("recip", (java.util.function.Function<Object, Object>) (x_0_i0) -> (((Double) (1.0)) / ((Double) (x_0_i0)))); put("Ring0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Ring.ringNumber); }};
}
