public class Data_Divide {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object dividePredicate = new java.util.LinkedHashMap<String, Object>() {{ put("divide", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> (java.util.function.Function<Object, Object>) (a_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object v2_4_i4 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(a_3_i3); return (((Boolean) (((java.util.function.Function<Object, Object>) (v_1_i1)).apply((((Data_Tuple.Tuple) v2_4_i4).value0)))) && ((Boolean) (((java.util.function.Function<Object, Object>) (v1_2_i2)).apply((((Data_Tuple.Tuple) v2_4_i4).value1))))); }).get()); put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i5) -> Data_Predicate.contravariantPredicate); }};
public static final Object divideOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("divide", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> (java.util.function.Function<Object, Object>) (a_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object v2_5_i5 = ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(a_4_i4); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_2_i2)).apply((((Data_Tuple.Tuple) v2_5_i5).value0))))).apply(((java.util.function.Function<Object, Object>) (v1_3_i3)).apply((((Data_Tuple.Tuple) v2_5_i5).value1))); }).get()); put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_1_i6) -> Data_Op.contravariantOp); }};
public static final Object divideEquivalence = new java.util.LinkedHashMap<String, Object>() {{ put("divide", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> (java.util.function.Function<Object, Object>) (a_3_i3) -> (java.util.function.Function<Object, Object>) (b_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object v2_5_i5 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(a_3_i3); return ((java.util.function.Supplier<Object>) () -> { Object v3_6_i6 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(b_4_i4); return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1_i1)).apply((((Data_Tuple.Tuple) v2_5_i5).value0)))).apply((((Data_Tuple.Tuple) v3_6_i6).value0)))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2_i2)).apply((((Data_Tuple.Tuple) v2_5_i5).value1)))).apply((((Data_Tuple.Tuple) v3_6_i6).value1))))); }).get(); }).get()); put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i7) -> Data_Equivalence.contravariantEquivalence); }};
public static final Object divideComparison = new java.util.LinkedHashMap<String, Object>() {{ put("divide", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> (java.util.function.Function<Object, Object>) (a_3_i3) -> (java.util.function.Function<Object, Object>) (b_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object v2_5_i5 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(a_3_i3); return ((java.util.function.Supplier<Object>) () -> { Object v3_6_i6 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(b_4_i4); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_7_i7 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1_i1)).apply((((Data_Tuple.Tuple) v2_5_i5).value0)))).apply((((Data_Tuple.Tuple) v3_6_i6).value0)); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_8_i8 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_2_i2)).apply((((Data_Tuple.Tuple) v2_5_i5).value1)))).apply((((Data_Tuple.Tuple) v3_6_i6).value1)); return ( ((Boolean) ((__local_var_7_i7 instanceof Data_Ordering.LT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_7_i7 instanceof Data_Ordering.GT))) ? new Data_Ordering.GT() : ( ((Boolean) ((__local_var_7_i7 instanceof Data_Ordering.EQ))) ? __local_var_8_i8 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get(); }).get(); }).get(); }).get()); put("Contravariant0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i9) -> Data_Comparison.contravariantComparison); }};
public static final Object divide = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("divide");
public static final Object divided = (java.util.function.Function<Object, Object>) (dictDivide_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivide_0_i0).get("divide"))).apply((java.util.function.Function<Object, Object>) (x_1_i1) -> x_1_i1);
}
