public class Data_Unfoldable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object unfoldrArrayImpl = FFI_STUB;
    public static Object unfoldrArrayImpl(Object... args) { return null; }

public static final Object unfoldr = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("unfoldr");
public static final Object unfoldableMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (b_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(b_1_i1); return ( ((Boolean) ((__local_var_2_i2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just((((Data_Tuple.Tuple) (((Data_Maybe.Just) __local_var_2_i2).value0)).value0)) : new Data_Maybe.Nothing()); }).get()); put("Unfoldable10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> Data_Unfoldable1.unfoldable1Maybe); }};
public static final Object unfoldableArray = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable.unfoldrArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_0_i0).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd)); put("Unfoldable10", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Unfoldable1.unfoldable1Array); }};
public static final Object replicate = (java.util.function.Function<Object, Object>) (dictUnfoldable_0_i0) -> (java.util.function.Function<Object, Object>) (n_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_0_i0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (i_3_i3) -> ( ((Boolean) ((((Integer) (i_3_i3)) <= ((Integer) (0))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(new Data_Tuple.Tuple(v_2_i2, (((Integer) (i_3_i3)) - ((Integer) (1))))))))).apply(n_1_i1);
public static final Object replicateA = (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> (java.util.function.Function<Object, Object>) (dictUnfoldable_1_i1) -> (java.util.function.Function<Object, Object>) (dictTraversable_2_i2) -> (java.util.function.Function<Object, Object>) (n_3_i3) -> (java.util.function.Function<Object, Object>) (m_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictTraversable_2_i2).get("sequence"))).apply(dictApplicative_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_1_i1).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (i_5_i5) -> ( ((Boolean) ((((Integer) (i_5_i5)) <= ((Integer) (0))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(new Data_Tuple.Tuple(m_4_i4, (((Integer) (i_5_i5)) - ((Integer) (1))))))))).apply(n_3_i3));
public static final Object none = (java.util.function.Function<Object, Object>) (dictUnfoldable_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_0_i0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (v_1_i1) -> new Data_Maybe.Nothing()))).apply(Data_Unit.unit);
public static final Object fromMaybe = (java.util.function.Function<Object, Object>) (dictUnfoldable_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_0_i0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (b_1_i1) -> ( ((Boolean) ((b_1_i1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(new Data_Tuple.Tuple((((Data_Maybe.Just) b_1_i1).value0), new Data_Maybe.Nothing())) : new Data_Maybe.Nothing()));
}
