public class Data_Ord_Min {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Min = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showMin = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Min ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object semigroupMin = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(v_1_i1))).apply(v1_2_i2); return ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.LT))) ? v_1_i1 : ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.EQ))) ? v_1_i1 : ( ((Boolean) ((v_3_i3 instanceof Data_Ordering.GT))) ? v1_2_i2 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()); }};
public static final Object newtypeMin = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidMin = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupMin1_1_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object v_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("compare"))).apply(v_2_i2))).apply(v1_3_i3); return ( ((Boolean) ((v_4_i4 instanceof Data_Ordering.LT))) ? v_2_i2 : ( ((Boolean) ((v_4_i4 instanceof Data_Ordering.EQ))) ? v_2_i2 : ( ((Boolean) ((v_4_i4 instanceof Data_Ordering.GT))) ? v1_3_i3 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("top")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i6) -> semigroupMin1_1_i5); }}; }).get();
public static final Object eqMin = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object ordMin = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqMin1_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(v_2_i2))).apply(v1_3_i3)); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> eqMin1_1_i1); }}; }).get();
}
