public class Data_Semigroup_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object genericSemigroupNoConstructors = new java.util.LinkedHashMap<String, Object>() {{ put("genericAppend'", (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> a_0_i0); }};
public static final Object genericSemigroupNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericAppend'", (java.util.function.Function<Object, Object>) (a_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> a_0_i0); }};
public static final Object genericSemigroupArgument = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericAppend'", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(v_1_i1))).apply(v1_2_i2)); }};
public static final Object genericAppendprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericAppend'");
public static final Object genericSemigroupConstructor = (java.util.function.Function<Object, Object>) (dictGenericSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericAppend'", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemigroup_0_i0).get("genericAppend'"))).apply(v_1_i1))).apply(v1_2_i2)); }};
public static final Object genericSemigroupProduct = (java.util.function.Function<Object, Object>) (dictGenericSemigroup_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemigroup1_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericAppend'", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> new Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemigroup_0_i0).get("genericAppend'"))).apply((((Data_Generic_Rep.Product) v_2_i2).value0)))).apply((((Data_Generic_Rep.Product) v1_3_i3).value0)), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemigroup1_1_i1).get("genericAppend'"))).apply((((Data_Generic_Rep.Product) v_2_i2).value1)))).apply((((Data_Generic_Rep.Product) v1_3_i3).value1)))); }};
public static final Object genericAppend = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericSemigroup_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("to"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericSemigroup_1_i1).get("genericAppend'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(y_3_i3)));
}
