public class Data_Const {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Const = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showConst = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Const ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object semiringConst = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> dictSemiring_0_i0;
public static final Object semigroupoidConst = new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> v1_1_i1); }};
public static final Object semigroupConst = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> dictSemigroup_0_i0;
public static final Object ringConst = (java.util.function.Function<Object, Object>) (dictRing_0_i0) -> dictRing_0_i0;
public static final Object ordConst = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> dictOrd_0_i0;
public static final Object newtypeConst = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidConst = (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> dictMonoid_0_i0;
public static final Object heytingAlgebraConst = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0_i0) -> dictHeytingAlgebra_0_i0;
public static final Object functorConst = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (m_1_i1) -> m_1_i1); }};
public static final Object invariantConst = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (m_2_i2) -> m_2_i2); }};
public static final Object euclideanRingConst = (java.util.function.Function<Object, Object>) (dictEuclideanRing_0_i0) -> dictEuclideanRing_0_i0;
public static final Object eqConst = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object eq1Const = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eq_1_i1 = ((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq"); return new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq1_2_i2) -> eq_1_i1); }}; }).get();
public static final Object ord1Const = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object compare_1_i1 = ((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"); return ((java.util.function.Supplier<Object>) () -> { Object eq1Const1_2_i4 = ((java.util.function.Supplier<Object>) () -> { Object eq_2_i2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)).get("eq"); return new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq1_3_i3) -> eq_2_i2); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd1_3_i5) -> compare_1_i1); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i6) -> eq1Const1_2_i4); }}; }).get(); }).get();
public static final Object commutativeRingConst = (java.util.function.Function<Object, Object>) (dictCommutativeRing_0_i0) -> dictCommutativeRing_0_i0;
public static final Object boundedConst = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> dictBounded_0_i0;
public static final Object booleanAlgebraConst = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0_i0) -> dictBooleanAlgebra_0_i0;
public static final Object applyConst = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(v_1_i1))).apply(v1_2_i2)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_1_i3) -> Data_Const.functorConst); }};
public static final Object applicativeConst = (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object applyConst1_1_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("append"))).apply(v_2_i2))).apply(v1_3_i3)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> Data_Const.functorConst); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (v_2_i6) -> ((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("mempty")); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> applyConst1_1_i5); }}; }).get();
}
