public class Data_Show_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object intercalate = FFI_STUB;
    public static Object intercalate(Object... args) { return null; }

public static final Object genericShowArgsNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericShowArgs", (java.util.function.Function<Object, Object>) (v_0_i0) -> new Object[]{}); }};
public static final Object genericShowArgsArgument = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShowArgs", (java.util.function.Function<Object, Object>) (v_1_i1) -> new Object[]{((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)}); }};
public static final Object genericShowArgs = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericShowArgs");
public static final Object genericShowArgsProduct = (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericShowArgs1_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShowArgs", (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup.concatArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShowArgs_0_i0).get("genericShowArgs"))).apply((((Data_Generic_Rep.Product) v_2_i2).value0))))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShowArgs1_1_i1).get("genericShowArgs"))).apply((((Data_Generic_Rep.Product) v_2_i2).value1)))); }};
public static final Object genericShowConstructor = (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0_i0) -> (java.util.function.Function<Object, Object>) (dictIsSymbol_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShow'", (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object ctor_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_1_i1).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); return ((java.util.function.Supplier<Object>) () -> { Object v1_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShowArgs_0_i0).get("genericShowArgs"))).apply(v_2_i2); return ( ((Boolean) ((((Integer) ((((Object[]) ((Object[]) (v1_4_i4))).length))) == ((Integer) (0))))) ? ctor_3_i3 : (((String) ((((String) ("(")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Show_Generic.intercalate)).apply(" "))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup.concatArray)).apply(new Object[]{ctor_3_i3}))).apply(v1_4_i4))))))) + ((String) (")")))); }).get(); }).get()); }};
public static final Object genericShowprime = (java.util.function.Function<Object, Object>) (dict_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dict_0_i0).get("genericShow'");
public static final Object genericShowNoConstructors = new java.util.LinkedHashMap<String, Object>() {{ put("genericShow'", (java.util.function.Function<Object, Object>) (a_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Show_Generic.genericShowNoConstructors).get("genericShow'"))).apply(a_0_i0)); }};
public static final Object genericShowSum = (java.util.function.Function<Object, Object>) (dictGenericShow_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericShow1_1_i1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShow'", (java.util.function.Function<Object, Object>) (v_2_i2) -> ( ((Boolean) ((v_2_i2 instanceof Data_Generic_Rep.Inl))) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShow_0_i0).get("genericShow'"))).apply((((Data_Generic_Rep.Inl) v_2_i2).value0)) : ( ((Boolean) ((v_2_i2 instanceof Data_Generic_Rep.Inr))) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShow1_1_i1).get("genericShow'"))).apply((((Data_Generic_Rep.Inr) v_2_i2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object genericShow = (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> (java.util.function.Function<Object, Object>) (dictGenericShow_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShow_1_i1).get("genericShow'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0_i0).get("from"))).apply(x_2_i2));
}
