public class Data_Comparison {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Comparison = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object semigroupComparison = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i7 = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (g_3_i3) -> (java.util.function.Function<Object, Object>) (x_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_5_i5 = ((java.util.function.Function<Object, Object>) (f_2_i2)).apply(x_4_i4); return ((java.util.function.Supplier<Object>) () -> { Object __local_var_6_i6 = ((java.util.function.Function<Object, Object>) (g_3_i3)).apply(x_4_i4); return ( ((Boolean) ((__local_var_5_i5 instanceof Data_Ordering.LT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_5_i5 instanceof Data_Ordering.GT))) ? new Data_Ordering.GT() : ( ((Boolean) ((__local_var_5_i5 instanceof Data_Ordering.EQ))) ? __local_var_6_i6 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get(); }).get()); }}; return (java.util.function.Function<Object, Object>) (x_3_i8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2_i7).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_0_i0)).apply(x_3_i8)))).apply(((java.util.function.Function<Object, Object>) (v1_1_i1)).apply(x_3_i8)); }).get()); }};
public static final Object newtypeComparison = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidComparison = new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> new Data_Ordering.EQ()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Comparison.semigroupComparison); }};
public static final Object defaultComparison = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare");
public static final Object contravariantComparison = new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1_i1)).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(y_3_i3))); }};
}
