public class Data_Functor_Flip {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Flip = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showFlip = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Flip ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object semigroupoidFlip = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_1_i1) -> (java.util.function.Function<Object, Object>) (v1_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0_i0).get("compose"))).apply(v1_2_i2))).apply(v_1_i1)); }};
public static final Object ordFlip = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> dictOrd_0_i0;
public static final Object newtypeFlip = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object functorFlip = (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply(f_1_i1))).apply((java.util.function.Function<Object, Object>) (x_3_i3) -> x_3_i3))).apply(v_2_i2)); }};
public static final Object eqFlip = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object contravariantFlip = (java.util.function.Function<Object, Object>) (dictProfunctor_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0_i0).get("dimap"))).apply(f_1_i1))).apply((java.util.function.Function<Object, Object>) (x_3_i3) -> x_3_i3))).apply(v_2_i2)); }};
public static final Object categoryFlip = (java.util.function.Function<Object, Object>) (dictCategory_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupoidFlip1_1_i4 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCategory_0_i0).get("Semigroupoid0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("compose"))).apply(v1_3_i3))).apply(v_2_i2)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("identity", ((java.util.LinkedHashMap<String, Object>) dictCategory_0_i0).get("identity")); put("Semigroupoid0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i5) -> semigroupoidFlip1_1_i4); }}; }).get();
public static final Object bifunctorFlip = (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (g_2_i2) -> (java.util.function.Function<Object, Object>) (v_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply(g_2_i2))).apply(f_1_i1))).apply(v_3_i3)); }};
public static final Object biapplyFlip = (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object bifunctorFlip1_1_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (g_3_i3) -> (java.util.function.Function<Object, Object>) (v_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("bimap"))).apply(g_3_i3))).apply(f_2_i2))).apply(v_4_i4)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_2_i6) -> (java.util.function.Function<Object, Object>) (v1_3_i7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(v_2_i6))).apply(v1_3_i7)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i8) -> bifunctorFlip1_1_i5); }}; }).get();
public static final Object biapplicativeFlip = (java.util.function.Function<Object, Object>) (dictBiapplicative_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object biapplyFlip1_1_i10 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0_i0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object bifunctorFlip1_2_i6 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_3_i3) -> (java.util.function.Function<Object, Object>) (g_4_i4) -> (java.util.function.Function<Object, Object>) (v_5_i5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2_i2).get("bimap"))).apply(g_4_i4))).apply(f_3_i3))).apply(v_5_i5)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_3_i7) -> (java.util.function.Function<Object, Object>) (v1_4_i8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("biapply"))).apply(v_3_i7))).apply(v1_4_i8)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i9) -> bifunctorFlip1_2_i6); }}; }).get(); }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("bipure", (java.util.function.Function<Object, Object>) (a_2_i11) -> (java.util.function.Function<Object, Object>) (b_3_i12) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0_i0).get("bipure"))).apply(b_3_i12))).apply(a_2_i11)); put("Biapply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i13) -> biapplyFlip1_1_i10); }}; }).get();
}
