public class Data_Ord_Down {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Down = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showDown = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Down ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object newtypeDown = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object eqDown = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object ordDown = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqDown1_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_2_i2) -> (java.util.function.Function<Object, Object>) (v1_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply(v_2_i2))).apply(v1_3_i3); return ( ((Boolean) ((__local_var_4_i4 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_4_i4 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((__local_var_4_i4 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i5) -> eqDown1_1_i1); }}; }).get();
public static final Object boundedDown = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object ordDown1_1_i7 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object eqDown1_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_3_i3) -> (java.util.function.Function<Object, Object>) (v1_4_i4) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_5_i5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("compare"))).apply(v_3_i3))).apply(v1_4_i4); return ( ((Boolean) ((__local_var_5_i5 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_5_i5 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((__local_var_5_i5 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }).get()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i6) -> eqDown1_2_i2); }}; }).get(); }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("top", ((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("bottom")); put("bottom", ((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("top")); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i8) -> ordDown1_1_i7); }}; }).get();
}
