public class Data_String_NonEmpty_CodeUnits {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object snoc = (java.util.function.Function<Object, Object>) (c_0_i0) -> (java.util.function.Function<Object, Object>) (s_1_i1) -> (((String) (s_1_i1)) + ((String) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.singleton)).apply(c_0_i0))));
public static final Object singleton = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.singleton)).apply(x_0_i0);
public static final Object takeWhile = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.countPrefix)).apply(f_0_i0))).apply(x_1_i1)))).apply(x_1_i1); return ( ((Boolean) (java.util.Objects.equals(__local_var_2_i2, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_2_i2)); }).get();
public static final Object lastIndexOfprime = (java.util.function.Function<Object, Object>) (pat_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.lastIndexOfprime)).apply(pat_0_i0); return (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(x_2_i2); return (java.util.function.Function<Object, Object>) (v_4_i4) -> ((java.util.function.Function<Object, Object>) (__local_var_3_i3)).apply(v_4_i4); }).get(); }).get();
public static final Object lastIndexOf = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.lastIndexOf)).apply(x_0_i0); return (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(v_2_i2); }).get();
public static final Object indexOfprime = (java.util.function.Function<Object, Object>) (pat_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.indexOfprime)).apply(pat_0_i0); return (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(x_2_i2); return (java.util.function.Function<Object, Object>) (v_4_i4) -> ((java.util.function.Function<Object, Object>) (__local_var_3_i3)).apply(v_4_i4); }).get(); }).get();
public static final Object indexOf = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.indexOf)).apply(x_0_i0); return (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(v_2_i2); }).get();
public static final Object length = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(x_0_i0);
public static final Object splitAt = (java.util.function.Function<Object, Object>) (i_0_i0) -> (java.util.function.Function<Object, Object>) (nes_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object v_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.splitAt)).apply(i_0_i0))).apply(nes_1_i1); return new java.util.LinkedHashMap<String, Object>() {{ put("before", ( ((Boolean) (java.util.Objects.equals(((java.util.LinkedHashMap<String, Object>) v_2_i2).get("before"), ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) v_2_i2).get("before")))); put("after", ( ((Boolean) (java.util.Objects.equals(((java.util.LinkedHashMap<String, Object>) v_2_i2).get("after"), ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) v_2_i2).get("after")))); }}; }).get();
public static final Object take = (java.util.function.Function<Object, Object>) (i_0_i0) -> (java.util.function.Function<Object, Object>) (nes_1_i1) -> ( ((Boolean) ((((Integer) (i_0_i0)) < ((Integer) (1))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply(i_0_i0))).apply(nes_1_i1)));
public static final Object takeRight = (java.util.function.Function<Object, Object>) (i_0_i0) -> (java.util.function.Function<Object, Object>) (nes_1_i1) -> ( ((Boolean) ((((Integer) (i_0_i0)) < ((Integer) (1))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply((((Integer) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(nes_1_i1))) - ((Integer) (i_0_i0)))))).apply(nes_1_i1)));
public static final Object toChar = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.toChar)).apply(x_0_i0);
public static final Object toCharArray = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.toCharArray)).apply(x_0_i0);
public static final Object toNonEmptyCharArray = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i2 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.toCharArray)).apply(x_0_i0); return ( ((Boolean) ((((Integer) ((((Object[]) ((Object[]) (__local_var_1_i1))).length))) > ((Integer) (0))))) ? new Data_Maybe.Just(__local_var_1_i1) : new Data_Maybe.Nothing()); }).get(); return ( ((Boolean) ((__local_var_1_i2 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) __local_var_1_i2).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()); }).get();
public static final Object uncons = (java.util.function.Function<Object, Object>) (nes_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("head", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(nes_0_i0)); put("tail", ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(1))).apply(nes_0_i0); return ( ((Boolean) (java.util.Objects.equals(__local_var_1_i1, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_1_i1)); }).get()); }};
public static final Object fromFoldable1 = (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(Data_Semigroup.semigroupString))).apply(Data_String_NonEmpty_CodeUnits.singleton);
public static final Object fromCharArray = (java.util.function.Function<Object, Object>) (v_0_i0) -> ( ((Boolean) ((((Integer) ((((Object[]) ((Object[]) (v_0_i0))).length))) == ((Integer) (0))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.fromCharArray)).apply(v_0_i0)));
public static final Object fromNonEmptyCharArray = (java.util.function.Function<Object, Object>) (x_0_i0) -> ( ((Boolean) ((((Integer) ((((Object[]) ((Object[]) (x_0_i0))).length))) == ((Integer) (0))))) ? ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get() : ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.fromCharArray)).apply(x_0_i0));
public static final Object dropWhile = (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.countPrefix)).apply(f_0_i0))).apply(x_1_i1)))).apply(x_1_i1); return ( ((Boolean) (java.util.Objects.equals(__local_var_2_i2, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_2_i2)); }).get();
public static final Object dropRight = (java.util.function.Function<Object, Object>) (i_0_i0) -> (java.util.function.Function<Object, Object>) (nes_1_i1) -> ( ((Boolean) ((((Integer) (i_0_i0)) >= ((Integer) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(nes_1_i1)))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply((((Integer) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(nes_1_i1))) - ((Integer) (i_0_i0)))))).apply(nes_1_i1)));
public static final Object drop = (java.util.function.Function<Object, Object>) (i_0_i0) -> (java.util.function.Function<Object, Object>) (nes_1_i1) -> ( ((Boolean) ((((Integer) (i_0_i0)) >= ((Integer) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(nes_1_i1)))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(i_0_i0))).apply(nes_1_i1)));
public static final Object countPrefix = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.countPrefix)).apply(x_0_i0); return (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(v_2_i2); }).get();
public static final Object cons = (java.util.function.Function<Object, Object>) (c_0_i0) -> (java.util.function.Function<Object, Object>) (s_1_i1) -> (((String) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.singleton)).apply(c_0_i0))) + ((String) (s_1_i1)));
public static final Object charAt = (java.util.function.Function<Object, Object>) (x_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.charAt)).apply(x_0_i0); return (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(v_2_i2); }).get();
}
