public class Data_Bifunctor_Join {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Join = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showJoin = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> (((String) ((((String) ("(Join ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")")))); }};
public static final Object ordJoin = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> dictOrd_0_i0;
public static final Object newtypeJoin = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object eqJoin = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> dictEq_0_i0;
public static final Object bifunctorJoin = (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_1_i1) -> (java.util.function.Function<Object, Object>) (v_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply(f_1_i1))).apply(f_1_i1))).apply(v_2_i2)); }};
public static final Object biapplyJoin = (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object bifunctorJoin1_1_i4 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_2_i2) -> (java.util.function.Function<Object, Object>) (v_3_i3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("bimap"))).apply(f_2_i2))).apply(f_2_i2))).apply(v_3_i3)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_2_i5) -> (java.util.function.Function<Object, Object>) (v1_3_i6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(v_2_i5))).apply(v1_3_i6)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> bifunctorJoin1_1_i4); }}; }).get();
public static final Object biapplicativeJoin = (java.util.function.Function<Object, Object>) (dictBiapplicative_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object biapplyJoin1_1_i9 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0_i0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object bifunctorJoin1_2_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_3_i3) -> (java.util.function.Function<Object, Object>) (v_4_i4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2_i2).get("bimap"))).apply(f_3_i3))).apply(f_3_i3))).apply(v_4_i4)); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_3_i6) -> (java.util.function.Function<Object, Object>) (v1_4_i7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("biapply"))).apply(v_3_i6))).apply(v1_4_i7)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i8) -> bifunctorJoin1_2_i5); }}; }).get(); }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a_2_i10) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0_i0).get("bipure"))).apply(a_2_i10))).apply(a_2_i10)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i11) -> biapplyJoin1_1_i9); }}; }).get();
}
