public class Data_Maybe_First {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object First = (java.util.function.Function<Object, Object>) (x_0_i0) -> x_0_i0;
public static final Object showFirst = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object showMaybe_1_i2 = new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1_i1) -> ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Just))) ? (((String) ((((String) ("(Just ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0_i0).get("show"))).apply((((Data_Maybe.Just) v_1_i1).value0))))))) + ((String) (")"))) : ( ((Boolean) ((v_1_i1 instanceof Data_Maybe.Nothing))) ? "Nothing" : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }}; return new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_2_i3) -> (((String) ((((String) ("First (")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) showMaybe_1_i2).get("show"))).apply(v_2_i3)))))) + ((String) (")")))); }}; }).get();
public static final Object semigroupFirst = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Just))) ? v_0_i0 : v1_1_i1)); }};
public static final Object ordFirst = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object eqMaybe1_1_i4 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2_i2) -> (java.util.function.Function<Object, Object>) (y_3_i3) -> ( ((Boolean) ((x_2_i2 instanceof Data_Maybe.Nothing))) ? (y_3_i3 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_2_i2 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_3_i3 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("eq"))).apply((((Data_Maybe.Just) x_2_i2).value0)))).apply((((Data_Maybe.Just) y_3_i3).value0)))))))))); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_2_i5) -> (java.util.function.Function<Object, Object>) (y_3_i6) -> ( ((Boolean) ((x_2_i5 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3_i6 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_3_i6 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_2_i5 instanceof Data_Maybe.Just))) && ((Boolean) ((y_3_i6 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0_i0).get("compare"))).apply((((Data_Maybe.Just) x_2_i5).value0)))).apply((((Data_Maybe.Just) y_3_i6).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> eqMaybe1_1_i4); }}; }).get();
public static final Object ord1First = Data_Maybe.ord1Maybe;
public static final Object newtypeFirst = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidFirst = new java.util.LinkedHashMap<String, Object>() {{ put("mempty", new Data_Maybe.Nothing()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe_First.semigroupFirst); }};
public static final Object monadFirst = Data_Maybe.monadMaybe;
public static final Object invariantFirst = Data_Maybe.invariantMaybe;
public static final Object functorFirst = Data_Maybe.functorMaybe;
public static final Object extendFirst = Data_Maybe.extendMaybe;
public static final Object eqFirst = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_1_i1) -> (java.util.function.Function<Object, Object>) (y_2_i2) -> ( ((Boolean) ((x_1_i1 instanceof Data_Maybe.Nothing))) ? (y_2_i2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1_i1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2_i2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0_i0).get("eq"))).apply((((Data_Maybe.Just) x_1_i1).value0)))).apply((((Data_Maybe.Just) y_2_i2).value0)))))))))); }};
public static final Object eq1First = Data_Maybe.eq1Maybe;
public static final Object boundedFirst = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object ordMaybe1_1_i9 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object eqMaybe1_2_i5 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_3_i3) -> (java.util.function.Function<Object, Object>) (y_4_i4) -> ( ((Boolean) ((x_3_i3 instanceof Data_Maybe.Nothing))) ? (y_4_i4 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_3_i3 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_4_i4 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2_i2).get("eq"))).apply((((Data_Maybe.Just) x_3_i3).value0)))).apply((((Data_Maybe.Just) y_4_i4).value0)))))))))); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_3_i6) -> (java.util.function.Function<Object, Object>) (y_4_i7) -> ( ((Boolean) ((x_3_i6 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_4_i7 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_4_i7 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_3_i6 instanceof Data_Maybe.Just))) && ((Boolean) ((y_4_i7 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("compare"))).apply((((Data_Maybe.Just) x_3_i6).value0)))).apply((((Data_Maybe.Just) y_4_i7).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3_i8) -> eqMaybe1_2_i5); }}; }).get(); }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("top", new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) dictBounded_0_i0).get("top"))); put("bottom", new Data_Maybe.Nothing()); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i10) -> ordMaybe1_1_i9); }}; }).get();
public static final Object bindFirst = Data_Maybe.bindMaybe;
public static final Object applyFirst = Data_Maybe.applyMaybe;
public static final Object applicativeFirst = Data_Maybe.applicativeMaybe;
public static final Object altFirst = new java.util.LinkedHashMap<String, Object>() {{ put("alt", (java.util.function.Function<Object, Object>) (v_0_i0) -> (java.util.function.Function<Object, Object>) (v1_1_i1) -> ( ((Boolean) ((v_0_i0 instanceof Data_Maybe.Just))) ? v_0_i0 : v1_1_i1)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> Data_Maybe.functorMaybe); }};
public static final Object plusFirst = new java.util.LinkedHashMap<String, Object>() {{ put("empty", new Data_Maybe.Nothing()); put("Alt0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe_First.altFirst); }};
public static final Object alternativeFirst = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Data_Maybe.applicativeMaybe); put("Plus1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Data_Maybe_First.plusFirst); }};
}
