public class Effect {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object bindE = FFI_STUB;
    public static Object bindE(Object... args) { return null; }
    public static Object forE = FFI_STUB;
    public static Object forE(Object... args) { return null; }
    public static Object foreachE = FFI_STUB;
    public static Object foreachE(Object... args) { return null; }
    public static Object pureE = FFI_STUB;
    public static Object pureE(Object... args) { return null; }
    public static Object untilE = FFI_STUB;
    public static Object untilE(Object... args) { return null; }
    public static Object whileE = FFI_STUB;
    public static Object whileE(Object... args) { return null; }

public static final Object monadEffect = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Effect.applicativeEffect); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> Effect.bindEffect); }};
public static final Object bindEffect = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Supplier<Object>) () -> { return ((java.util.function.Supplier<Object>) ((java.util.function.Function<Object, Object>) f).apply(((java.util.function.Supplier<Object>) a).get())).get(); }); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Effect.applyEffect); }};
public static final Object applyEffect = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (a_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object f_prime__2_i2 = f_0_i0; return ((java.util.function.Supplier<Object>) () -> { Object a_prime__3_i3 = a_1_i1; return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.applicativeEffect).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__2_i2)).apply(a_prime__3_i3)); }).get(); }).get()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i4) -> Effect.functorEffect); }};
public static final Object applicativeEffect = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Supplier<Object>) () -> a); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> Effect.applyEffect); }};
public static final Object functorEffect = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0_i0) -> (java.util.function.Function<Object, Object>) (a_1_i1) -> ((java.util.function.Supplier<Object>) () -> { Object a_prime__2_i2 = a_1_i1; return ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(a_prime__2_i2); }).get()); }};
public static final Object semigroupEffect = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a_1_i1) -> (java.util.function.Function<Object, Object>) (b_2_i2) -> ((java.util.function.Supplier<Object>) () -> { Object f_prime__3_i4 = ((java.util.function.Supplier<Object>) () -> { Object a_prime__3_i3 = a_1_i1; return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0_i0).get("append"))).apply(a_prime__3_i3); }).get(); return ((java.util.function.Supplier<Object>) () -> { Object a_prime__4_i5 = b_2_i2; return ((java.util.function.Function<Object, Object>) (f_prime__3_i4)).apply(a_prime__4_i5); }).get(); }).get()); }};
public static final Object monoidEffect = (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object semigroupEffect1_1_i7 = ((java.util.function.Supplier<Object>) () -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a_2_i2) -> (java.util.function.Function<Object, Object>) (b_3_i3) -> ((java.util.function.Supplier<Object>) () -> { Object f_prime__4_i5 = ((java.util.function.Supplier<Object>) () -> { Object a_prime__4_i4 = a_2_i2; return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1_i1).get("append"))).apply(a_prime__4_i4); }).get(); return ((java.util.function.Supplier<Object>) () -> { Object a_prime__5_i6 = b_3_i3; return ((java.util.function.Function<Object, Object>) (f_prime__4_i5)).apply(a_prime__5_i6); }).get(); }).get()); }}; }).get(); return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.function.Supplier<Object>) () -> { Object __local_var_2_i8 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0_i0).get("mempty"); return __local_var_2_i8; }).get()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2_i9) -> semigroupEffect1_1_i7); }}; }).get();
}
