public class Effect_Class_Console {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object warnShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (dictShow_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.warn)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1_i1).get("show"))).apply(x_2_i2)));
public static final Object warn = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.warn)).apply(x_1_i1));
public static final Object timeLog = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.timeLog)).apply(x_1_i1));
public static final Object timeEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.timeEnd)).apply(x_1_i1));
public static final Object time = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.time)).apply(x_1_i1));
public static final Object logShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (dictShow_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1_i1).get("show"))).apply(x_2_i2)));
public static final Object log = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(x_1_i1));
public static final Object infoShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (dictShow_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.info)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1_i1).get("show"))).apply(x_2_i2)));
public static final Object info = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.info)).apply(x_1_i1));
public static final Object groupEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(Effect_Console.groupEnd);
public static final Object groupCollapsed = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.groupCollapsed)).apply(x_1_i1));
public static final Object group = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.group)).apply(x_1_i1));
public static final Object grouped = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> ((java.util.function.Supplier<Object>) () -> { Object Monad0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object Bind1_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad0_1_i1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return ((java.util.function.Supplier<Object>) () -> { Object groupEnd1_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(Effect_Console.groupEnd); return ((java.util.function.Supplier<Object>) () -> { Object Applicative0_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad0_1_i1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (name_5_i5) -> (java.util.function.Function<Object, Object>) (inner_6_i6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2_i2).get("bind"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.group)).apply(name_5_i5))))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_7_i7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2_i2).get("bind"))).apply(inner_6_i6))).apply((java.util.function.Function<Object, Object>) (result_8_i8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2_i2).get("bind"))).apply(groupEnd1_3_i3))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_9_i9) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_4_i4).get("pure"))).apply(result_8_i8)))); }).get(); }).get(); }).get(); }).get();
public static final Object errorShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (dictShow_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1_i1).get("show"))).apply(x_2_i2)));
public static final Object error = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(x_1_i1));
public static final Object debugShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (dictShow_1_i1) -> (java.util.function.Function<Object, Object>) (x_2_i2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.debug)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1_i1).get("show"))).apply(x_2_i2)));
public static final Object debug = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> (java.util.function.Function<Object, Object>) (x_1_i1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.debug)).apply(x_1_i1));
public static final Object clear = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(Effect_Console.clear);
}
